// Hand-curated from OpenFlights airlines.dat (public domain), ~100 highest-volume carriers.
// To refresh the base map quarterly: node scripts/generate-airline-codes.mjs
// To correct individual entries immediately: add to OVERRIDE below (takes precedence over GENERATED).

const OVERRIDE: Record<string, { iata: string; name: string }> = {
  SWR: { iata: 'LX', name: 'Swiss International Air Lines' },
  TGW: { iata: 'TR', name: 'Scoot' },
};

// --- BEGIN GENERATED AIRLINES ---
const GENERATED: Record<string, { iata: string; name: string }> = {
  "AAA": { iata: "AN", name: "Ansett Australia" },
  "AAF": { iata: "ZI", name: "Aigle Azur" },
  "AAH": { iata: "AQ", name: "Aloha Airlines" },
  "AAL": { iata: "AA", name: "American Airlines" },
  "AAN": { iata: "WD", name: "Amsterdam Airlines" },
  "AAR": { iata: "OZ", name: "Asiana Airlines" },
  "AAS": { iata: "4K", name: "Askari Aviation" },
  "AAW": { iata: "8U", name: "Afriqiyah Airways" },
  "AAY": { iata: "G4", name: "Allegiant Air" },
  "ABD": { iata: "CC", name: "Air Atlanta Icelandic" },
  "ABI": { iata: "U1", name: "Aviabus" },
  "ABL": { iata: "BX", name: "Air Busan" },
  "ABQ": { iata: "ED", name: "Airblue" },
  "ABS": { iata: "9T", name: "Transwest Air" },
  "ABY": { iata: "G9", name: "Air Arabia" },
  "ACA": { iata: "AC", name: "Air Canada" },
  "ACI": { iata: "SB", name: "Air Caledonie International" },
  "ACP": { iata: "8V", name: "Astral Aviation" },
  "ADE": { iata: "ZY", name: "Ada Air" },
  "ADH": { iata: "AP", name: "Air One" },
  "ADO": { iata: "HD", name: "Hokkaido International Airlines" },
  "ADR": { iata: "JP", name: "Adria Airways" },
  "AEA": { iata: "UX", name: "Air Europa" },
  "AEB": { iata: "EM", name: "Aero Benin" },
  "AEE": { iata: "A3", name: "Aegean Airlines" },
  "AEL": { iata: "PE", name: "Air Europe" },
  "AER": { iata: "KO", name: "Alaska Central Express" },
  "AEU": { iata: "5W", name: "Astraeus" },
  "AEW": { iata: "VV", name: "Aerosvit Airlines" },
  "AEY": { iata: "I9", name: "Air Italy" },
  "AFG": { iata: "FG", name: "Ariana Afghan Airlines" },
  "AFL": { iata: "SU", name: "Aeroflot Russian Airlines" },
  "AFR": { iata: "AF", name: "Air France" },
  "AGV": { iata: "7T", name: "Air Glaciers" },
  "AHO": { iata: "HH", name: "Air Hamburg (AHO)" },
  "AHY": { iata: "J2", name: "Azerbaijan Airlines" },
  "AIA": { iata: "U3", name: "Avies" },
  "AIC": { iata: "AI", name: "Air India Limited" },
  "AIQ": { iata: "FD", name: "Thai AirAsia" },
  "AIZ": { iata: "IZ", name: "Arkia Israel Airlines" },
  "AJM": { iata: "JM", name: "Air Jamaica" },
  "AJX": { iata: "NQ", name: "Air Japan" },
  "AKL": { iata: "4A", name: "Air Kiribati" },
  "ALK": { iata: "UL", name: "SriLankan Airlines" },
  "AMC": { iata: "KM", name: "Air Malta" },
  "AML": { iata: "QM", name: "Air Malawi" },
  "AMU": { iata: "NX", name: "Air Macau" },
  "AMX": { iata: "AM", name: "AeroMéxico" },
  "ANA": { iata: "NH", name: "All Nippon Airways" },
  "ANE": { iata: "YW", name: "Air Nostrum" },
  "ANG": { iata: "PX", name: "Air Niugini" },
  "ANK": { iata: "EL", name: "Air Nippon" },
  "ANO": { iata: "TL", name: "Airnorth" },
  "ANT": { iata: "4N", name: "Air North Charter - Canada" },
  "ANZ": { iata: "NZ", name: "Air New Zealand" },
  "APW": { iata: "JW", name: "Arrow Air" },
  "ARD": { iata: "2B", name: "Aerocondor" },
  "ARE": { iata: "4C", name: "Aires" },
  "ARF": { iata: "GV", name: "Aero Flight" },
  "ARG": { iata: "AR", name: "Aerolineas Argentinas" },
  "ASA": { iata: "AS", name: "Alaska Airlines" },
  "ASD": { iata: "4D", name: "Air Sinai" },
  "ASH": { iata: "YV", name: "Mesa Airlines" },
  "ASL": { iata: "JU", name: "Air Serbia" },
  "ASQ": { iata: "EV", name: "Atlantic Southeast Airlines" },
  "ASZ": { iata: "OB", name: "Astrakhan Airlines" },
  "ATC": { iata: "TC", name: "Air Tanzania" },
  "ATM": { iata: "FO", name: "Airlines Of Tasmania" },
  "AUA": { iata: "OS", name: "Austrian Airlines" },
  "AUB": { iata: "IQ", name: "Augsburg Airways" },
  "AUH": { iata: "MO", name: "Abu Dhabi Amiri Flight" },
  "AUI": { iata: "PS", name: "Ukraine International Airlines" },
  "AUL": { iata: "5N", name: "Aeroflot-Nord" },
  "AUR": { iata: "GR", name: "Aurigny Air Services" },
  "AUT": { iata: "AU", name: "Austral Lineas Aereas" },
  "AVA": { iata: "AV", name: "Avianca - Aerovias Nacionales de Colombia" },
  "AVN": { iata: "NF", name: "Air Vanuatu" },
  "AWA": { iata: "Y5", name: "Asia Wings" },
  "AWE": { iata: "HP", name: "America West Airlines" },
  "AWI": { iata: "ZW", name: "Air Wisconsin" },
  "AWM": { iata: "AW", name: "Asian Wings Airways" },
  "AWQ": { iata: "QZ", name: "Indonesia AirAsia" },
  "AWU": { iata: "7E", name: "Aeroline GmbH" },
  "AWW": { iata: "6G", name: "Air Wales" },
  "AXB": { iata: "IX", name: "Air India Express" },
  "AXL": { iata: "XT", name: "Air Exel" },
  "AXM": { iata: "AK", name: "AirAsia" },
  "AXZ": { iata: "JY", name: "Aereonautica militare" },
  "AYZ": { iata: "3G", name: "Atlant-Soyuz Airlines" },
  "AZA": { iata: "AZ", name: "Alitalia" },
  "AZN": { iata: "Z8", name: "Amaszonas" },
  "AZU": { iata: "AD", name: "Azul" },
  "AZW": { iata: "UM", name: "Air Zimbabwe" },
  "BAG": { iata: "DI", name: "dba" },
  "BAW": { iata: "BA", name: "British Airways" },
  "BBC": { iata: "BG", name: "Biman Bangladesh Airlines" },
  "BBO": { iata: "F7", name: "Flybaboo" },
  "BBR": { iata: "S3", name: "Santa Barbara Airlines" },
  "BCC": { iata: "8B", name: "BusinessAir" },
  "BCY": { iata: "WX", name: "CityJet" },
  "BEE": { iata: "BE", name: "Flybe" },
  "BER": { iata: "AB", name: "Air Berlin" },
  "BGD": { iata: "B9", name: "Air Bangladesh" },
  "BHP": { iata: "4T", name: "Belair Airlines" },
  "BHS": { iata: "UP", name: "Bahamasair" },
  "BIE": { iata: "DR", name: "Air Mediterranee" },
  "BIH": { iata: "BS", name: "British International Helicopters" },
  "BKP": { iata: "PG", name: "Bangkok Airways" },
  "BLF": { iata: "KF", name: "Blue1" },
  "BLS": { iata: "JV", name: "Bearskin Lake Air Service" },
  "BLV": { iata: "B3", name: "Bellview Airlines" },
  "BLX": { iata: "6B", name: "TUIfly Nordic" },
  "BMA": { iata: "BD", name: "bmi" },
  "BMI": { iata: "WW", name: "bmibaby" },
  "BMJ": { iata: "CH", name: "Bemidji Airlines" },
  "BMM": { iata: "8A", name: "Atlas Blue" },
  "BON": { iata: "JA", name: "Air Bosna" },
  "BOT": { iata: "BP", name: "Air Botswana" },
  "BPA": { iata: "BV", name: "Blue Panorama Airlines" },
  "BQB": { iata: "BQ", name: "Buquebus Líneas Aéreas" },
  "BRG": { iata: "8E", name: "Bering Air" },
  "BRQ": { iata: "UZ", name: "El-Buraq Air Transport" },
  "BRU": { iata: "B2", name: "Belavia Belarusian Airlines" },
  "BSA": { iata: "BZ", name: "Black Stallion Airways" },
  "BSX": { iata: "5B", name: "Bassaka airlines" },
  "BTA": { iata: "XE", name: "ExpressJet" },
  "BTI": { iata: "BT", name: "Air Baltic" },
  "BTQ": { iata: "4B", name: "Boutique Air (Priv)" },
  "BTV": { iata: "7P", name: "Metro Batavia" },
  "BUB": { iata: "ZB", name: "Air Bourbon" },
  "BUU": { iata: "BU", name: "Baikotovitchestrian Airlines" },
  "BVT": { iata: "J8", name: "Berjaya Air" },
  "BWA": { iata: "BW", name: "Caribbean Airlines" },
  "BWG": { iata: "QW", name: "Blue Wings" },
  "BZE": { iata: "GB", name: "BRAZIL AIR" },
  "BZH": { iata: "DB", name: "Brit Air" },
  "CAL": { iata: "CI", name: "China Airlines" },
  "CAP": { iata: "C2", name: "CanXplorer" },
  "CAW": { iata: "MN", name: "Comair" },
  "CAY": { iata: "KX", name: "Cayman Airways" },
  "CCA": { iata: "CA", name: "Air China" },
  "CCC": { iata: "CB", name: "CCML Airlines" },
  "CCM": { iata: "XK", name: "Corse-Mediterranee" },
  "CDG": { iata: "SC", name: "Shandong Airlines" },
  "CDN": { iata: "CP", name: "Canadian Airlines" },
  "CDP": { iata: "Q6", name: "Aero Condor Peru" },
  "CEB": { iata: "5J", name: "Cebu Pacific" },
  "CES": { iata: "MU", name: "China Eastern Airlines" },
  "CFE": { iata: "CJ", name: "BA CityFlyer" },
  "CFG": { iata: "DE", name: "Condor Flugdienst" },
  "CGP": { iata: "8L", name: "Cargo Plus Aviation" },
  "CHB": { iata: "PN", name: "West Air China" },
  "CHH": { iata: "HU", name: "Hainan Airlines" },
  "CHP": { iata: "6A", name: "Consorcio Aviaxsa" },
  "CHQ": { iata: "RP", name: "Chautauqua Airlines" },
  "CIF": { iata: "1F", name: "CB Airways UK ( Interliging Flights )" },
  "CIM": { iata: "QI", name: "Cimber Air" },
  "CIX": { iata: "G3", name: "City Connexion Airlines" },
  "CJC": { iata: "9L", name: "Colgan Air" },
  "CLH": { iata: "CL", name: "Lufthansa CityLine" },
  "CLI": { iata: "XG", name: "Calima Aviacion" },
  "CLW": { iata: "C0", name: "Centralwings" },
  "CMI": { iata: "CS", name: "Continental Micronesia" },
  "CMP": { iata: "CM", name: "Copa Airlines" },
  "COA": { iata: "CO", name: "Continental Airlines" },
  "COM": { iata: "OH", name: "Comair" },
  "CPA": { iata: "CX", name: "Cathay Pacific" },
  "CPN": { iata: "RV", name: "Caspian Airlines" },
  "CPZ": { iata: "CP", name: "Compass Airlines" },
  "CQH": { iata: "9S", name: "Spring Airlines" },
  "CQN": { iata: "OQ", name: "Chongqing Airlines" },
  "CRK": { iata: "HX", name: "Hong Kong Airlines" },
  "CRL": { iata: "SS", name: "Corsairfly" },
  "CSA": { iata: "OK", name: "Czech Airlines" },
  "CSC": { iata: "3U", name: "Sichuan Airlines" },
  "CSH": { iata: "FM", name: "Shanghai Airlines" },
  "CSN": { iata: "CZ", name: "China Southern Airlines" },
  "CSZ": { iata: "ZH", name: "Shenzhen Airlines" },
  "CTN": { iata: "OU", name: "Croatia Airlines" },
  "CUA": { iata: "HR", name: "China United Airlines" },
  "CUB": { iata: "CU", name: "Cubana de Aviación" },
  "CVA": { iata: "CV", name: "Air Chathams" },
  "CWK": { iata: "KR", name: "Comores Airlines" },
  "CWM": { iata: "CW", name: "Air Marshall Islands" },
  "CXA": { iata: "MF", name: "Xiamen Airlines" },
  "CYD": { iata: "ZA", name: "Access Air" },
  "CYH": { iata: "3Q", name: "Yunnan Airlines" },
  "CYP": { iata: "CY", name: "Cyprus Airways" },
  "CZV": { iata: "6V", name: "Via Conectia Airlines" },
  "DAH": { iata: "AH", name: "Air Algerie" },
  "DAL": { iata: "DL", name: "Delta Air Lines" },
  "DAO": { iata: "D3", name: "Daallo Airlines" },
  "DAT": { iata: "SN", name: "Brussels Airlines" },
  "DHI": { iata: "KI", name: "Adam Air" },
  "DJB": { iata: "D8", name: "Djibouti Airlines" },
  "DKH": { iata: "HO", name: "Juneyao Airlines" },
  "DLA": { iata: "EN", name: "Air Dolomiti" },
  "DLH": { iata: "LH", name: "Lufthansa" },
  "DMO": { iata: "E3", name: "Domodedovo Airlines" },
  "DNV": { iata: "D9", name: "Aeroflot-Don" },
  "DOA": { iata: "DO", name: "Dominicana de Aviaci" },
  "DOB": { iata: "QD", name: "Dobrolet" },
  "DRD": { iata: "NM", name: "Air Madrid" },
  "DRK": { iata: "KB", name: "Druk Air" },
  "DRU": { iata: "6R", name: "Alrosa Mirny Air Enterprise" },
  "DSM": { iata: "4M", name: "LAN Argentina" },
  "DSY": { iata: "DH", name: "Dennis Sky" },
  "DTA": { iata: "DT", name: "TAAG Angola Airlines" },
  "DTR": { iata: "DX", name: "DAT Danish Air Transport" },
  "DWA": { iata: "KP", name: "Dense Airways" },
  "DWT": { iata: "0D", name: "Darwin Airline" },
  "EAL": { iata: "EA", name: "European Air Express" },
  "EAV": { iata: "13", name: "Eastern Atlantic Virtual Airlines" },
  "ECA": { iata: "UI", name: "Eurocypria Airlines" },
  "EDW": { iata: "WK", name: "Edelweiss Air" },
  "EEA": { iata: "EU", name: "Empresa Ecuatoriana De Aviacion" },
  "EEU": { iata: "GJ", name: "Eurofly Service" },
  "EFA": { iata: "EF", name: "Far Eastern Air Transport" },
  "EGF": { iata: "MQ", name: "American Eagle Airlines" },
  "EIA": { iata: "EZ", name: "Evergreen International Airlines" },
  "EIN": { iata: "EI", name: "Aer Lingus" },
  "EJA": { iata: "1I", name: "NetJets" },
  "ELA": { iata: "DK", name: "Eastland Air" },
  "ELL": { iata: "OV", name: "Estonian Air" },
  "ELO": { iata: "K2", name: "Eurolot" },
  "ELY": { iata: "LY", name: "El Al Israel Airlines" },
  "ERO": { iata: "7L", name: "Sun D'Or" },
  "ERR": { iata: "7H", name: "Era Alaska" },
  "ERT": { iata: "B8", name: "Eritrean Airlines" },
  "ESK": { iata: "NE", name: "SkyEurope" },
  "ESR": { iata: "ZE", name: "Eastar Jet" },
  "ETD": { iata: "EY", name: "Etihad Airways" },
  "ETH": { iata: "ET", name: "Ethiopian Airlines" },
  "EUV": { iata: "ES", name: "EuropeSky" },
  "EVA": { iata: "BR", name: "EVA Air" },
  "EWG": { iata: "EW", name: "Eurowings" },
  "EXS": { iata: "LS", name: "Jet2.com" },
  "EZE": { iata: "T3", name: "Eastern Airways" },
  "EZY": { iata: "U2", name: "easyJet" },
  "FAB": { iata: "7F", name: "First Air" },
  "FBL": { iata: "F1", name: "Fly Brasil" },
  "FCA": { iata: "DP", name: "First Choice Airways" },
  "FDB": { iata: "FZ", name: "Fly Dubai" },
  "FFM": { iata: "FY", name: "Firefly" },
  "FFT": { iata: "F9", name: "Frontier Airlines" },
  "FFV": { iata: "5H", name: "Fly540" },
  "FHE": { iata: "HW", name: "Hello" },
  "FHI": { iata: "FH", name: "FlyHigh Airlines Ireland (FH)" },
  "FIF": { iata: "OF", name: "Air Finland" },
  "FIN": { iata: "AY", name: "Finnair" },
  "FJI": { iata: "FJ", name: "Air Pacific" },
  "FLG": { iata: "9E", name: "Pinnacle Airlines" },
  "FLI": { iata: "RC", name: "Atlantic Airways" },
  "FLT": { iata: "B5", name: "Flightline" },
  "FLZ": { iata: "QH", name: "Air Florida" },
  "FOS": { iata: "VY", name: "Formosa Airlines" },
  "FOX": { iata: "FX", name: "FOX Linhas Aereas" },
  "FPT": { iata: "PO", name: "FlyPortugal" },
  "FRE": { iata: "FP", name: "Freedom Air" },
  "FRF": { iata: "FF", name: "Fly France" },
  "FTA": { iata: "2F", name: "Frontier Flying Service" },
  "FWI": { iata: "TX", name: "Air Caraïbes" },
  "FWL": { iata: "RF", name: "Florida West International Airways" },
  "FXI": { iata: "NY", name: "Air Iceland" },
  "FXX": { iata: "FU", name: "Felix Airways" },
  "GAI": { iata: "3R", name: "Moskovia Airlines" },
  "GAO": { iata: "DC", name: "Golden Air" },
  "GAP": { iata: "2P", name: "Air Philippines" },
  "GBA": { iata: "GF", name: "Gulf Air Bahrain" },
  "GBK": { iata: "GY", name: "Gabon Airlines" },
  "GBL": { iata: "GT", name: "GB Airways" },
  "GDR": { iata: "GP", name: "Gadair European Airlines" },
  "GEC": { iata: "LH", name: "Lufthansa Cargo" },
  "GER": { iata: "GM", name: "German International Air Lines" },
  "GFG": { iata: "QB", name: "Georgian National Airlines" },
  "GFY": { iata: "XX", name: "Greenfly" },
  "GHB": { iata: "G0", name: "Ghana International Airlines" },
  "GIA": { iata: "GA", name: "Garuda Indonesia" },
  "GIE": { iata: "E4", name: "Elysian Airlines" },
  "GIP": { iata: "2U", name: "Air Guinee Express" },
  "GJS": { iata: "G7", name: "GoJet Airlines" },
  "GLA": { iata: "ZK", name: "Great Lakes Airlines" },
  "GLG": { iata: "2K", name: "Aerolineas Galapagos (Aerogal)" },
  "GLO": { iata: "G3", name: "Gol Transportes Aéreos" },
  "GLP": { iata: "GH", name: "Globus" },
  "GMI": { iata: "ST", name: "Germania" },
  "GOW": { iata: "G8", name: "Go Air" },
  "GRL": { iata: "GL", name: "Air Greenland" },
  "GSM": { iata: "B4", name: "Flyglobespan" },
  "GTA": { iata: "E8", name: "City Airways" },
  "GTI": { iata: "5Y", name: "Atlas Air" },
  "GUY": { iata: "GG", name: "Air Guyane" },
  "GWI": { iata: "4U", name: "Germanwings" },
  "GWY": { iata: "U5", name: "USA3000 Airlines" },
  "GXG": { iata: "GX", name: "GermanXL" },
  "GZP": { iata: "4G", name: "Gazpromavia" },
  "HAG": { iata: "H6", name: "Hageland Aviation Services" },
  "HAL": { iata: "HA", name: "Hawaiian Airlines" },
  "HAM": { iata: "2T", name: "Haiti Ambassador Airlines" },
  "HCW": { iata: "V9", name: "Star1 Airlines" },
  "HDA": { iata: "KA", name: "Dragonair" },
  "HEJ": { iata: "T4", name: "Hellas Jet" },
  "HER": { iata: "UD", name: "Hex'Air" },
  "HFR": { iata: "8H", name: "Heli France" },
  "HHI": { iata: "4R", name: "Hamburg International" },
  "HKE": { iata: "UO", name: "Hong Kong Express Airways" },
  "HLF": { iata: "HF", name: "Hapagfly" },
  "HLX": { iata: "X3", name: "TUIfly" },
  "HNX": { iata: "HN", name: "Hankook Airline" },
  "HVN": { iata: "VN", name: "Vietnam Airlines" },
  "HYM": { iata: "HC", name: "Himalayan Airlines" },
  "HZA": { iata: "BN", name: "Horizon Airlines" },
  "IAA": { iata: "IO", name: "Indonesian Airlines" },
  "IAC": { iata: "IC", name: "Indian Airlines" },
  "IAW": { iata: "IA", name: "Iraqi Airways" },
  "IBB": { iata: "NT", name: "Binter Canarias" },
  "IBE": { iata: "IB", name: "Iberia Airlines" },
  "IBS": { iata: "I2", name: "Iberia Express" },
  "IBU": { iata: "I9", name: "Indigo" },
  "IBX": { iata: "FW", name: "Ibex Airlines" },
  "ICE": { iata: "FI", name: "Icelandair" },
  "ICL": { iata: "5C", name: "CAL Cargo Air Lines" },
  "IDS": { iata: "I5", name: "Indonesia Sky" },
  "IGO": { iata: "6E", name: "IndiGo Airlines" },
  "IIR": { iata: "Z5", name: "INAVIA Internacional" },
  "IKA": { iata: "GI", name: "Itek Air" },
  "ILN": { iata: "D6", name: "Interair South Africa" },
  "IMP": { iata: "HT", name: "Hellenic Imperial Airways" },
  "INE": { iata: "9I", name: "International Europe" },
  "IPV": { iata: "PA", name: "Parmiss Airlines (IPV)" },
  "IRA": { iata: "IR", name: "Iran Air" },
  "IRC": { iata: "EP", name: "Iran Aseman Airlines" },
  "IRK": { iata: "Y9", name: "Kish Air" },
  "IRM": { iata: "W5", name: "Mahan Air" },
  "ISK": { iata: "3L", name: "Intersky" },
  "ISR": { iata: "6H", name: "Israir" },
  "ISS": { iata: "IG", name: "Meridiana" },
  "ISV": { iata: "WC", name: "Islena De Inversiones" },
  "ISW": { iata: "IF", name: "Islas Airways" },
  "ISX": { iata: "IP", name: "Island Spirit" },
  "ITK": { iata: "ID", name: "Interlink Airlines" },
  "ITX": { iata: "IK", name: "Imair Airlines" },
  "IWA": { iata: "ZM", name: "Apache Air" },
  "IWD": { iata: "TY", name: "Iberworld" },
  "IYE": { iata: "IY", name: "Yemenia" },
  "JAA": { iata: "EG", name: "Japan Asia Airways" },
  "JAB": { iata: "W9", name: "Air Bagan" },
  "JAF": { iata: "JF", name: "Jetairfly" },
  "JAI": { iata: "9W", name: "Jet Airways" },
  "JAL": { iata: "JL", name: "Japan Airlines Domestic" },
  "JAS": { iata: "JD", name: "Japan Air System" },
  "JAZ": { iata: "JO", name: "JALways" },
  "JBA": { iata: "JB", name: "Helijet" },
  "JBU": { iata: "B6", name: "JetBlue Airways" },
  "JET": { iata: "IV", name: "Wind Jet" },
  "JEX": { iata: "JC", name: "JAL Express" },
  "JFU": { iata: "8J", name: "Jet4You" },
  "JJA": { iata: "7C", name: "Jeju Air" },
  "JKK": { iata: "JK", name: "Spanair" },
  "JNA": { iata: "LJ", name: "Jin Air" },
  "JOR": { iata: "0B", name: "Blue Air" },
  "JOY": { iata: "JR", name: "Joy Air" },
  "JSA": { iata: "3K", name: "Jetstar Asia Airways" },
  "JSR": { iata: "JX", name: "Jusur airways" },
  "JST": { iata: "JQ", name: "Jetstar Airways" },
  "JTA": { iata: "NU", name: "Japan Transocean Air" },
  "JTO": { iata: "NR", name: "Jettor Airlines" },
  "JZA": { iata: "QK", name: "Air Canada Jazz" },
  "JZR": { iata: "J9", name: "Jazeera Airways" },
  "KAC": { iata: "KU", name: "Kuwait Airways" },
  "KAL": { iata: "KE", name: "Korean Air" },
  "KAP": { iata: "9K", name: "Cape Air" },
  "KBR": { iata: "K7", name: "KoralBlue Airlines" },
  "KEN": { iata: "M5", name: "Kenmore Air" },
  "KFR": { iata: "IT", name: "Kingfisher Airlines" },
  "KGL": { iata: "7K", name: "Kogalymavia Air Company" },
  "KGO": { iata: "ZC", name: "Korongo Airlines" },
  "KHB": { iata: "H8", name: "Dalavia" },
  "KHK": { iata: "KH", name: "Kharkiv Airlines" },
  "KIL": { iata: "GW", name: "Kuban Airlines" },
  "KIS": { iata: "C3", name: "Contact Air" },
  "KJC": { iata: "7B", name: "Krasnojarsky Airlines" },
  "KKK": { iata: "KK", name: "Atlasjet" },
  "KLC": { iata: "WA", name: "KLM Cityhopper" },
  "KLM": { iata: "KL", name: "KLM Royal Dutch Airlines" },
  "KMF": { iata: "RQ", name: "Kam Air" },
  "KNE": { iata: "XY", name: "Nas Air" },
  "KNI": { iata: "KD", name: "KD Avia" },
  "KOL": { iata: "CQ", name: "SOCHI AIR" },
  "KOQ": { iata: "K1", name: "Kostromskie avialinii" },
  "KOR": { iata: "JS", name: "Air Koryo" },
  "KQA": { iata: "KQ", name: "Kenya Airways" },
  "KRP": { iata: "V3", name: "Carpatair" },
  "KSY": { iata: "KY", name: "KSY" },
  "KZK": { iata: "9Y", name: "Air Kazakhstan" },
  "KZR": { iata: "KC", name: "Air Astana" },
  "KZU": { iata: "GO", name: "Kuzu Airlines Cargo" },
  "LAA": { iata: "LN", name: "Libyan Arab Airlines" },
  "LAJ": { iata: "KJ", name: "British Mediterranean Airways" },
  "LAM": { iata: "LM", name: "Linhas A" },
  "LAN": { iata: "LA", name: "LAN Airlines" },
  "LAO": { iata: "QV", name: "Lao Airlines" },
  "LAP": { iata: "PZ", name: "TAM Mercosur" },
  "LBC": { iata: "LV", name: "Albanian Airlines" },
  "LBL": { iata: "L8", name: "Line Blue" },
  "LBT": { iata: "BJ", name: "Nouvel Air Tunisie" },
  "LDA": { iata: "NG", name: "Lauda Air" },
  "LGL": { iata: "LG", name: "Luxair" },
  "LGW": { iata: "HE", name: "Luftfahrtgesellschaft Walter" },
  "LHN": { iata: "EO", name: "Express One International" },
  "LIA": { iata: "LI", name: "Leeward Islands Air Transport" },
  "LIL": { iata: "TE", name: "FlyLal" },
  "LIX": { iata: "C4", name: "LionXpress" },
  "LJJ": { iata: "L4", name: "Luchsh Airlines" },
  "LLM": { iata: "YL", name: "Yamal Airlines" },
  "LMM": { iata: "LQ", name: "LCM AIRLINES" },
  "LMU": { iata: "UJ", name: "AlMasria Universal Airlines" },
  "LNE": { iata: "XL", name: "Aerolane" },
  "LNI": { iata: "JT", name: "Lion Mentari Airlines" },
  "LOC": { iata: "ZQ", name: "Locair" },
  "LOF": { iata: "AX", name: "Trans States Airlines" },
  "LOO": { iata: "PQ", name: "LSM Airlines" },
  "LOT": { iata: "LO", name: "LOT Polish Airlines" },
  "LPE": { iata: "LP", name: "LAN Peru" },
  "LPR": { iata: "MJ", name: "L" },
  "LRC": { iata: "LR", name: "LACSA" },
  "LTE": { iata: "XO", name: "LTE International Airways" },
  "LTO": { iata: "L3", name: "LTU Austria" },
  "LTR": { iata: "L5", name: "Lufttransport" },
  "LTU": { iata: "LT", name: "Air Lituanica" },
  "LTY": { iata: "LE", name: "Liberty Airways" },
  "LUR": { iata: "TD", name: "Atlantis European Airways" },
  "LXP": { iata: "LU", name: "LAN Express" },
  "LXR": { iata: "LK", name: "Air Luxor" },
  "LZB": { iata: "FB", name: "Bulgaria Air" },
  "MAA": { iata: "M7", name: "MasAir" },
  "MAC": { iata: "R5", name: "Malta Air Charter" },
  "MAH": { iata: "MA", name: "Malév" },
  "MAI": { iata: "L6", name: "Mauritania Airlines International" },
  "MAK": { iata: "IN", name: "MAT Macedonian Airlines" },
  "MAS": { iata: "MH", name: "Malaysia Airlines" },
  "MAU": { iata: "MK", name: "Air Mauritius" },
  "MAV": { iata: "ML", name: "Maldivo Airlines" },
  "MCK": { iata: "CC", name: "Macair Airlines" },
  "MDA": { iata: "AE", name: "Mandarin Airlines" },
  "MDG": { iata: "MD", name: "Air Madagascar" },
  "MDL": { iata: "RI", name: "Mandala Airlines" },
  "MDO": { iata: "D1", name: "Domenican Airlines" },
  "MDV": { iata: "2M", name: "Moldavian Airlines" },
  "MDW": { iata: "JI", name: "Midway Airlines" },
  "MEA": { iata: "ME", name: "Middle East Airlines" },
  "MEP": { iata: "YX", name: "Midwest Airlines" },
  "MES": { iata: "XJ", name: "Mesaba Airlines" },
  "MGL": { iata: "OM", name: "MIAT Mongolian Airlines" },
  "MGX": { iata: "YM", name: "Montenegro Airlines" },
  "MJG": { iata: "DF", name: "Michael Airlines" },
  "MJX": { iata: "4L", name: "Euroline" },
  "MKD": { iata: "6F", name: "MAT Airways" },
  "MKG": { iata: "P8", name: "Air Mekong" },
  "MKU": { iata: "WP", name: "Island Air (WP)" },
  "MLA": { iata: "Q5", name: "40-Mile Air" },
  "MLD": { iata: "9U", name: "Air Moldova" },
  "MMM": { iata: "8M", name: "Myanmar Airways International" },
  "MNA": { iata: "MZ", name: "Merpati Nusantara Airlines" },
  "MNB": { iata: "MB", name: "MNG Airlines" },
  "MNO": { iata: "JE", name: "Mango" },
  "MNP": { iata: "SM", name: "Spirit of Manila Airlines" },
  "MON": { iata: "ZB", name: "Monarch Airlines" },
  "MOV": { iata: "NN", name: "VIM Airlines" },
  "MPD": { iata: "A7", name: "Air Plus Comet" },
  "MPE": { iata: "5T", name: "Canadian North" },
  "MPH": { iata: "MP", name: "Martinair" },
  "MRS": { iata: "Y8", name: "Marusya Airways" },
  "MSI": { iata: "M9", name: "Motor Sich" },
  "MSR": { iata: "MS", name: "Egyptair" },
  "MVD": { iata: "KV", name: "Kavminvodyavia" },
  "MWA": { iata: "MY", name: "Midwest Airlines (Egypt)" },
  "MXA": { iata: "MX", name: "Mexicana de Aviaci" },
  "MXD": { iata: "OD", name: "Malindo Air" },
  "MXI": { iata: "I6", name: "MexicanaLink" },
  "MXL": { iata: "8M", name: "Maxair" },
  "MYD": { iata: "MW", name: "Maya Island Air" },
  "MYT": { iata: "VZ", name: "MyTravel Airways" },
  "NAK": { iata: "Q9", name: "Arik Niger" },
  "NAS": { iata: "UE", name: "Nasair" },
  "NAX": { iata: "DY", name: "Norwegian Air Shuttle" },
  "NCR": { iata: "N8", name: "National Air Cargo" },
  "NDC": { iata: "LF", name: "FlyNordic" },
  "NEA": { iata: "EJ", name: "New England Airlines" },
  "NGB": { iata: "NJ", name: "Nordic Global Airlines" },
  "NIA": { iata: "NP", name: "Nile Air" },
  "NIG": { iata: "AJ", name: "Aero Contractors" },
  "NJS": { iata: "NC", name: "National Jet Systems" },
  "NKF": { iata: "8N", name: "Barents AirLink" },
  "NKS": { iata: "NK", name: "Spirit Airlines" },
  "NLH": { iata: "DU", name: "Norwegian Long Haul AS" },
  "NLY": { iata: "HG", name: "Niki" },
  "NMB": { iata: "SW", name: "Air Namibia" },
  "NMI": { iata: "LW", name: "Pacific Wings" },
  "NOK": { iata: "DD", name: "Nok Air" },
  "NSE": { iata: "9R", name: "SATENA" },
  "NTJ": { iata: "2N", name: "NextJet" },
  "NTW": { iata: "CE", name: "Nationwide Airlines" },
  "NVR": { iata: "1I", name: "Novair" },
  "NWA": { iata: "NW", name: "Northwest Airlines" },
  "NXB": { iata: "XB", name: "NEXT Brasil" },
  "OAB": { iata: "O1", name: "Orbit Airlines Azerbaijan" },
  "OAE": { iata: "OY", name: "Omni Air International" },
  "OAL": { iata: "OA", name: "Olympic Airlines" },
  "OAW": { iata: "2L", name: "Helvetic Airways" },
  "OCA": { iata: "R7", name: "Aserca Airlines" },
  "OEA": { iata: "OX", name: "Orient Thai Airlines" },
  "OGN": { iata: "QO", name: "Origin Pacific Airways" },
  "OHK": { iata: "O8", name: "Oasis Hong Kong Airlines" },
  "OHY": { iata: "8Q", name: "Onur Air" },
  "OLA": { iata: "OJ", name: "Overland Airways" },
  "OLT": { iata: "OL", name: "Ostfriesische Lufttransport" },
  "OMA": { iata: "WY", name: "Oman Air" },
  "OME": { iata: "MR", name: "Homer Air" },
  "ONE": { iata: "O6", name: "Oceanair" },
  "OOM": { iata: "Z4", name: "Zoom Airlines" },
  "ORB": { iata: "R2", name: "Orenburg Airlines" },
  "ORC": { iata: "OI", name: "Orchid Airlines" },
  "OTJ": { iata: "X5", name: "Fly Romania" },
  "OZJ": { iata: "O7", name: "Ozjet Airlines" },
  "PAL": { iata: "PR", name: "Philippine Airlines" },
  "PAO": { iata: "PH", name: "Polynesian Airlines" },
  "PBA": { iata: "9Q", name: "PB Air" },
  "PCO": { iata: "8P", name: "Pacific Coastal Airline" },
  "PDC": { iata: "BK", name: "Potomac Air" },
  "PDT": { iata: "PI", name: "Piedmont Airlines (1948-1989)" },
  "PEC": { iata: "Q8", name: "Pacific East Asia Cargo Airlines" },
  "PEL": { iata: "OT", name: "Aeropelican Air Services" },
  "PEN": { iata: "KS", name: "Peninsula Airways" },
  "PGA": { iata: "NI", name: "Portugalia" },
  "PGT": { iata: "PC", name: "Pegasus Airlines" },
  "PIA": { iata: "PK", name: "Pakistan International Airlines" },
  "PIC": { iata: "BL", name: "Jetstar Pacific" },
  "PLI": { iata: "PL", name: "Aeroper" },
  "PLR": { iata: "J3", name: "Northwestern Air" },
  "PMT": { iata: "U4", name: "PMTair" },
  "PMW": { iata: "I7", name: "Paramount Airways" },
  "PNR": { iata: "PV", name: "PAN Air" },
  "POE": { iata: "PD", name: "Porter Airlines" },
  "PPL": { iata: "OP", name: "Air Pegasus" },
  "PQW": { iata: "WQ", name: "PanAm World Airways" },
  "PRF": { iata: "PW", name: "Precision Air" },
  "PUA": { iata: "PU", name: "PLUNA" },
  "PYB": { iata: "0P", name: "All America BOPY" },
  "QAX": { iata: "C3", name: "QatXpress" },
  "QER": { iata: "Q3", name: "SOCHI AIR CHATER" },
  "QFA": { iata: "QF", name: "Qantas" },
  "QTR": { iata: "QR", name: "Qatar Airways" },
  "QXE": { iata: "QX", name: "Horizon Air" },
  "RAB": { iata: "RN", name: "Rainbow Air (RAI)" },
  "RAC": { iata: "VJ", name: "Royal Air Cambodge" },
  "RAE": { iata: "YS", name: "Régional" },
  "RAM": { iata: "AT", name: "Royal Air Maroc" },
  "RAR": { iata: "GZ", name: "Air Rarotonga" },
  "RAW": { iata: "KG", name: "Royal Airways" },
  "RAY": { iata: "RY", name: "Rainbow Air Canada" },
  "RBA": { iata: "BI", name: "Royal Brunei Airlines" },
  "RBG": { iata: "E5", name: "Air Arabia Egypt" },
  "RBY": { iata: "V2", name: "Vision Airlines (V2)" },
  "REA": { iata: "RE", name: "Aer Arann" },
  "REP": { iata: "P7", name: "Regional Paraguaya" },
  "REU": { iata: "UU", name: "Air Austral" },
  "RFJ": { iata: "RL", name: "Royal Falcon" },
  "RGG": { iata: "1E", name: "TransRussiaAirlines" },
  "RIT": { iata: "6K", name: "Asian Spirit" },
  "RJA": { iata: "RJ", name: "Royal Jordanian" },
  "RKA": { iata: "RK", name: "Air Afrique" },
  "RLA": { iata: "A5", name: "Airlinair" },
  "RLN": { iata: "QL", name: "Aero Lanka" },
  "RNA": { iata: "RA", name: "Royal Nepal Airlines" },
  "RNE": { iata: "20", name: "Air Salone" },
  "RNV": { iata: "U8", name: "Armavia" },
  "RNX": { iata: "1T", name: "1Time Airline" },
  "RNY": { iata: "RM", name: "Rainbow Air US" },
  "RON": { iata: "ON", name: "Nauru Air Corporation" },
  "ROT": { iata: "RO", name: "Tarom" },
  "RPA": { iata: "RW", name: "Republic Airlines" },
  "RPB": { iata: "P5", name: "AeroRep" },
  "RPH": { iata: "RH", name: "Republic Express Airlines" },
  "RPO": { iata: "RX", name: "Rainbow Air Polynesia" },
  "RRJ": { iata: "R8", name: "AirRussia" },
  "RSH": { iata: "S2", name: "Air Sahara" },
  "RSR": { iata: "BF", name: "Aero-Service" },
  "RSU": { iata: "5L", name: "Aerosur" },
  "RSY": { iata: "H5", name: "I-Fly" },
  "RUE": { iata: "RU", name: "Rainbow Air Euro" },
  "RUS": { iata: "C9", name: "Cirrus Airlines" },
  "RWD": { iata: "WB", name: "Rwandair Express" },
  "RWW": { iata: "ER", name: "Fly Europa" },
  "RWZ": { iata: "WZ", name: "Red Wings" },
  "RXA": { iata: "ZL", name: "Regional Express" },
  "RXR": { iata: "RR", name: "REXAIR VIRTUEL" },
  "RYN": { iata: "RD", name: "Ryan International Airlines" },
  "RYR": { iata: "FR", name: "Ryanair" },
  "RZO": { iata: "S4", name: "SATA International" },
  "SAA": { iata: "SA", name: "South African Airways" },
  "SAE": { iata: "Q4", name: "SOCHI AIR EXPRESS" },
  "SAI": { iata: "NL", name: "Shaheen Air International" },
  "SAL": { iata: "S0", name: "Spike Airlines" },
  "SAS": { iata: "SK", name: "Scandinavian Airlines System" },
  "SAT": { iata: "SP", name: "SATA Air Acores" },
  "SBD": { iata: "S8", name: "Snowbird Airlines" },
  "SBI": { iata: "S7", name: "S7 Airlines" },
  "SBS": { iata: "BB", name: "Seaborne Airlines" },
  "SCO": { iata: "TZ", name: "Scoot" },
  "SCW": { iata: "TF", name: "Malmö Aviation" },
  "SCX": { iata: "SY", name: "Sun Country Airlines" },
  "SDM": { iata: "FV", name: "Rossiya-Russian Airlines" },
  "SDR": { iata: "CF", name: "City Airline" },
  "SEH": { iata: "G3", name: "Sky Express" },
  "SEJ": { iata: "SG", name: "Spicejet" },
  "SEU": { iata: "SE", name: "XL Airways France" },
  "SEY": { iata: "HM", name: "Air Seychelles" },
  "SFJ": { iata: "7G", name: "Star Flyer" },
  "SGG": { iata: "DN", name: "Senegal Airlines" },
  "SGY": { iata: "N5", name: "Skagway Air Service" },
  "SHA": { iata: "SH", name: "Sharp Airlines" },
  "SIA": { iata: "SQ", name: "Singapore Airlines" },
  "SIB": { iata: "5M", name: "Sibaviatrans" },
  "SIH": { iata: "SI", name: "Skynet Airlines" },
  "SJM": { iata: "7R", name: "Svyaz Rossiya" },
  "SJO": { iata: "IJ", name: "Spring Airlines Japan" },
  "SJS": { iata: "76", name: "Southjet" },
  "SJU": { iata: "UQ", name: "Skyjet Airlines" },
  "SJY": { iata: "SJ", name: "Sriwijaya Air" },
  "SKU": { iata: "H2", name: "Sky Airline" },
  "SKV": { iata: "RS", name: "Sky Regional" },
  "SKW": { iata: "OO", name: "SkyWest" },
  "SKX": { iata: "JZ", name: "Skyways Express" },
  "SKY": { iata: "BC", name: "Skymark Airlines" },
  "SLC": { iata: "SO", name: "Salsa d\\\\'Haiti" },
  "SLI": { iata: "5D", name: "Aerolitoral" },
  "SLK": { iata: "MI", name: "SilkAir" },
  "SLM": { iata: "PY", name: "Surinam Airways" },
  "SMJ": { iata: "Z3", name: "Avient Aviation" },
  "SMX": { iata: "XM", name: "Alitalia Express" },
  "SMY": { iata: "ZS", name: "Sama Airlines" },
  "SNB": { iata: "NB", name: "Sterling Airlines" },
  "SNC": { iata: "2Q", name: "Air Cargo Carriers" },
  "SNJ": { iata: "6J", name: "Skynet Asia Airways" },
  "SOL": { iata: "IE", name: "Solomon Airlines" },
  "SOV": { iata: "6W", name: "Saratov Aviation Division" },
  "SOZ": { iata: "HZ", name: "Sat Airlines" },
  "SPM": { iata: "PJ", name: "Air Saint Pierre" },
  "SQC": { iata: "SQ", name: "Singapore Airlines Cargo" },
  "SQH": { iata: "K5", name: "SeaPort Airlines" },
  "SRH": { iata: "FT", name: "Siem Reap Airways" },
  "SRQ": { iata: "DG", name: "South East Asian Airlines" },
  "SSA": { iata: "AG", name: "All America US" },
  "SSV": { iata: "5G", name: "Skyservice Airlines" },
  "STP": { iata: "8F", name: "STP Airways" },
  "STU": { iata: "FS", name: "Servicios de Transportes A" },
  "SUD": { iata: "SD", name: "Sudan Airways" },
  "SUW": { iata: "ZA", name: "Interavia Airlines" },
  "SVA": { iata: "SV", name: "Saudi Arabian Airlines" },
  "SVR": { iata: "U6", name: "Ural Airlines" },
  "SWA": { iata: "WN", name: "Southwest Airlines" },
  "SWD": { iata: "A4", name: "Southern Winds Airlines" },
  "SWR": { iata: "SR", name: "Swissair" },
  "SWV": { iata: "WV", name: "Swe Fly" },
  "SXR": { iata: "XW", name: "Sky Express" },
  "SXS": { iata: "XQ", name: "SunExpress" },
  "SYL": { iata: "R3", name: "Aircompany Yakutia" },
  "SYR": { iata: "RB", name: "Syrian Arab Airlines" },
  "SYX": { iata: "AL", name: "Skywalk Airlines" },
  "TAE": { iata: "EQ", name: "TAME" },
  "TAK": { iata: "U9", name: "Tatarstan Airlines" },
  "TAM": { iata: "JJ", name: "TAM Brazilian Airlines" },
  "TAO": { iata: "VW", name: "Aeromar" },
  "TAP": { iata: "TP", name: "TAP Portugal" },
  "TAR": { iata: "TU", name: "Tunisair" },
  "TAT": { iata: "TA", name: "Grupo TACA" },
  "TBZ": { iata: "TB", name: "TrasBrasil" },
  "TCF": { iata: "S5", name: "Shuttle America" },
  "TCG": { iata: "T2", name: "Thai Air Cargo" },
  "TCV": { iata: "VR", name: "TACV" },
  "TCW": { iata: "FQ", name: "Thomas Cook Airlines" },
  "TCX": { iata: "MT", name: "Thomas Cook Airlines" },
  "TFL": { iata: "OR", name: "Arkefly" },
  "TGW": { iata: "TT", name: "Tiger Airways Australia" },
  "TGZ": { iata: "A9", name: "Georgian Airways" },
  "THA": { iata: "TG", name: "Thai Airways International" },
  "THI": { iata: "TI", name: "TransHolding" },
  "THS": { iata: "TH", name: "TransBrasil Airlines" },
  "THT": { iata: "TN", name: "Air Tahiti Nui" },
  "THY": { iata: "TK", name: "Turkish Airlines" },
  "TIB": { iata: "8R", name: "TRIP Linhas A" },
  "TJA": { iata: "TJ", name: "T.J. Air" },
  "TJT": { iata: "T7", name: "Twin Jet" },
  "TMA": { iata: "TL", name: "Trans Mediterranean Airlines" },
  "TNA": { iata: "GE", name: "TransAsia Airways" },
  "TNM": { iata: "3P", name: "Tiara Air" },
  "TNU": { iata: "M8", name: "TransNusa Air" },
  "TOK": { iata: "CG", name: "Airlines PNG" },
  "TOM": { iata: "BY", name: "Thomsonfly" },
  "TOS": { iata: "PM", name: "Tropic Air" },
  "TPA": { iata: "QT", name: "TAMPA" },
  "TRA": { iata: "HV", name: "Transavia Holland" },
  "TRS": { iata: "FL", name: "AirTran Airways" },
  "TSC": { iata: "TS", name: "Air Transat" },
  "TSO": { iata: "UN", name: "Transaero Airlines" },
  "TUA": { iata: "T5", name: "Turkmenistan Airlines" },
  "TUI": { iata: "UG", name: "Tuninter" },
  "TUS": { iata: "M3", name: "ABSA - Aerolinhas Brasileiras" },
  "TVF": { iata: "TO", name: "Transavia France" },
  "TVS": { iata: "QS", name: "Travel Service" },
  "TWB": { iata: "TW", name: "Tway Airlines" },
  "TWN": { iata: "EC", name: "Avialeasing Aviation Company" },
  "TXW": { iata: "TQ", name: "Texas Wings" },
  "TYR": { iata: "VO", name: "Tyrolean Airways" },
  "TYS": { iata: "YO", name: "TransHolding System" },
  "UAE": { iata: "EK", name: "Emirates" },
  "UAL": { iata: "UA", name: "United Airlines" },
  "UBA": { iata: "UB", name: "Myanma Airways" },
  "UBD": { iata: "4H", name: "United Airways" },
  "UCA": { iata: "C5", name: "CommutAir" },
  "UDC": { iata: "5D", name: "DonbassAero" },
  "UGX": { iata: "QU", name: "East African" },
  "UIA": { iata: "B7", name: "Uni Air" },
  "UKM": { iata: "UF", name: "UM Airlines" },
  "UPA": { iata: "GS", name: "Air Foyle" },
  "URN": { iata: "3T", name: "Turan Air" },
  "USA": { iata: "US", name: "US Airways" },
  "UTA": { iata: "UT", name: "UTair Aviation" },
  "UTY": { iata: "QQ", name: "Alliance Airlines" },
  "UWW": { iata: "II", name: "LSM International" },
  "UZB": { iata: "HY", name: "Uzbekistan Airways" },
  "VAS": { iata: "V8", name: "ATRAN Cargo Airlines" },
  "VAX": { iata: "ZV", name: "V Air" },
  "VBW": { iata: "2J", name: "Air Burkina" },
  "VCV": { iata: "V0", name: "Conviasa" },
  "VDA": { iata: "VI", name: "Volga-Dnepr Airlines" },
  "VEX": { iata: "TV", name: "Virgin Express" },
  "VGN": { iata: "VK", name: "Virgin Nigeria Airways" },
  "VIA": { iata: "V1", name: "VIA Líneas Aéreas" },
  "VIM": { iata: "VL", name: "Air VIA" },
  "VIR": { iata: "VS", name: "Virgin Atlantic Airways" },
  "VKH": { iata: "VQ", name: "Viking Hellas" },
  "VKJ": { iata: "KT", name: "VickJet" },
  "VLE": { iata: "VE", name: "Volare Airlines" },
  "VLG": { iata: "VY", name: "Vueling Airlines" },
  "VLK": { iata: "XF", name: "Vladivostok Air" },
  "VLM": { iata: "VG", name: "VLM Airlines" },
  "VLO": { iata: "LC", name: "Varig Log" },
  "VLU": { iata: "VF", name: "Valuair" },
  "VNP": { iata: "VH", name: "Virgin Pacific" },
  "VOE": { iata: "V7", name: "VOLOTEA Airways" },
  "VOI": { iata: "Y4", name: "Volaris" },
  "VOZ": { iata: "VA", name: "Virgin Australia" },
  "VRD": { iata: "VX", name: "Virgin America" },
  "VRN": { iata: "RG", name: "VRG Linhas Aereas" },
  "VSP": { iata: "VP", name: "VASP" },
  "VSV": { iata: "DV", name: "Scat Air" },
  "VTA": { iata: "VT", name: "Air Tahiti" },
  "VTI": { iata: "UK", name: "Air Vistara" },
  "VUN": { iata: "VU", name: "Air Ivoire" },
  "VVC": { iata: "5Z", name: "VivaColombia" },
  "VVM": { iata: "ZG", name: "Viva Macau" },
  "VVN": { iata: "47", name: "88" },
  "VWA": { iata: "YY", name: "Virginwings" },
  "WAL": { iata: "WA", name: "Western Airlines" },
  "WAU": { iata: "WU", name: "Wizz Air Ukraine" },
  "WBA": { iata: "FC", name: "Finncomm Airlines" },
  "WEB": { iata: "WJ", name: "WebJet Linhas A" },
  "WEN": { iata: "WR", name: "WestJet Encore" },
  "WER": { iata: "W4", name: "AeroWorld" },
  "WIF": { iata: "WF", name: "Widerøe" },
  "WJA": { iata: "WS", name: "WestJet" },
  "WLC": { iata: "2W", name: "Welcome Air" },
  "WOA": { iata: "WO", name: "World Airways" },
  "WON": { iata: "IW", name: "Wings Air" },
  "WSS": { iata: "W3", name: "World Scale Airlines" },
  "WTA": { iata: "FK", name: "Africa West" },
  "WVL": { iata: "8Z", name: "Wizz Air Hungary" },
  "WZZ": { iata: "W6", name: "Wizz Air" },
  "XAN": { iata: "78", name: "Southjet cargo" },
  "XAU": { iata: "XA", name: "XAIR USA" },
  "XAX": { iata: "D7", name: "AirAsia X" },
  "XLA": { iata: "JN", name: "Excel Airways" },
  "XPT": { iata: "XP", name: "XPTO" },
  "YCC": { iata: "YC", name: "Ciel Canadien" },
  "YCP": { iata: "CN", name: "Canadian National Airways" },
  "YEL": { iata: "YE", name: "Yellowtail" },
  "YZZ": { iata: "YZ", name: "LSM AIRLINES" },
  "ZCS": { iata: "77", name: "Southjet connect" },
  "ZNA": { iata: "ZN", name: "Zenith International Airline" },
  "ZTF": { iata: "7M", name: "Mongolian International Air Lines" },
  "ZTT": { iata: "Z6", name: "ZABAIKAL AIRLINES" },
  "ZXY": { iata: "ZX", name: "Japan Regio" },
  "ZZZ": { iata: "ZP", name: "Zabaykalskii Airlines" },
};
// --- END GENERATED AIRLINES ---

// Reconstruct the internal map safely combining generated data and overrides
const AIRLINES = new Map<string, { iata: string; name: string }>(Object.entries(GENERATED));
for (const [key, val] of Object.entries(OVERRIDE)) {
  AIRLINES.set(key, val);
}

/**
 * Parse an ICAO-style callsign into prefix and numeric suffix.
 * Normalizes whitespace and case. Returns null for non-standard formats.
 */
export function parseCallsign(cs: string): { prefix: string; number: string } | null {
  const trimmed = cs.trim().toUpperCase();
  const m = trimmed.match(/^([A-Z]{2,4})(\d.*)$/);
  if (!m) return null;
  return { prefix: m[1] ?? '', number: m[2] ?? '' };
}

/**
 * Look up IATA code and airline name by ICAO 3-letter prefix.
 * Returns undefined for unknown or military callsigns.
 */
export function icaoToIata(icaoPrefix: string): { iata: string; name: string } | undefined {
  return AIRLINES.get(icaoPrefix.toUpperCase());
}

/**
 * Convert an ICAO callsign (e.g. "UAE528") to its IATA equivalent (e.g. "EK528").
 * Returns null if the prefix is unknown (military, charter, etc.).
 */
export function toIataCallsign(cs: string): { callsign: string; name: string } | null {
  const p = parseCallsign(cs);
  if (!p) return null;
  const a = icaoToIata(p.prefix);
  if (!a) return null;
  return { callsign: a.iata + p.number, name: a.name };
}
