/**
 * Server-rendered differentiation copy for dashboard shells (#7380).
 *
 * Variant subdomain dashboards share one SPA shell; without unique body
 * prose their HTML is ~98% identical and compete as near-duplicates.
 * These paragraphs are injected into the persistent SEO summary + noscript
 * fallback (and the AI-crawler stub on variant roots) so each host has
 * 300–500 words of genuine, product-accurate differentiation.
 */

export type VariantSeoKey = 'full' | 'tech' | 'finance' | 'commodity' | 'happy' | 'energy';

export const VARIANT_SEO_PARAGRAPHS: Record<VariantSeoKey, readonly string[]> = {
  full: [
    'Yerküre is the full-spectrum real-time global intelligence dashboard: one browser workspace that combines geopolitical conflict tracking, military and civil aviation, maritime AIS, undersea cable and infrastructure maps, markets, climate hazards, cyber signals, and open-source news into a single live situation picture. Analysts, journalists, researchers, and operators use it to see how distant events connect before they harden into headlines.',
    'On the map you can follow conflict zones and protest activity alongside earthquake and wildfire alerts, power-outage clusters, and strategic infrastructure such as military bases, nuclear facilities, and subsea cables. Aviation layers surface military and commercial flights; maritime layers track ships through chokepoints and high-risk waters. Country deep-dives open resilience, risk, and source-backed context for more than 190 states without leaving the dashboard.',
    'Market and prediction panels sit beside the geospatial view so price moves, central-bank signals, commodities, and prediction-market odds can be read against the same map context that shows tankers, jets, and crisis corridors. Government-spending and macro indicators help separate noise from policy-relevant shifts. The goal is not another news feed — it is a continuously updating OSINT workbench with auditable upstream sources.',
    'Reference surfaces outside the live map keep the same evidence standard: country intelligence pages, maritime chokepoint briefs, crisis trackers, live tools, research reports, and an audited source catalog. Agents and developers can also use the MCP server and REST API documented on the site. Yerküre is open source and free to start; Pro unlocks deeper analysis without hiding the core map. Specialized sibling monitors focus on tech, finance, commodities, energy infrastructure, and constructive global progress; this full dashboard remains the canonical geopolitics and multi-domain intelligence surface at www.worldmonitor.app/dashboard for humans and crawlers alike.',
    'If you need a single citeable URL for multi-domain situation awareness — conflicts, markets, flights, ships, infrastructure, and climate hazards together — use this full dashboard rather than a specialized sibling. That separation is intentional: tech, finance, commodity, energy, and happy monitors carry their own summaries so crawlers do not treat six shells as near-duplicates.',
  ],
  tech: [
    'Tech Monitor is the Yerküre variant built for AI, cloud, and startup-ecosystem intelligence. Instead of a general geopolitics desk, this dashboard centers technology companies, AI research labs, accelerators, funding signals, datacenter and cloud infrastructure, service-status events, and tech-market moves so product, policy, and research teams can watch the industry as one live system.',
    'Follow major AI labs and platform vendors on the map and in dedicated panels: headquarters and campus footprints, conference and launch calendars, layoff and hiring waves, and funding-round context that explains why a region suddenly matters. Startup-ecosystem layers highlight clusters and accelerators, while cloud and datacenter mapping shows where compute capacity and connectivity concentrate — the physical substrate behind model training and global SaaS delivery.',
    'Tech Monitor also tracks the market and operational side of the stack: tech equities and sector heat, outage and status incidents that cascade across dependents, and regulatory or policy items that reshape AI deployment. News aggregation is tuned to technology and AI sources rather than general world wires, so the same globe metaphor serves an industry beat instead of a conflict desk.',
    'Typical users include AI policy staff, venture and corporate strategy teams, reliability engineers watching vendor concentration, and reporters covering platform power. Use Tech Monitor when your question is about AI labs, startup geography, or cloud infrastructure rather than kinetic conflict. The same evidence standards apply — attributable feeds and transparent layer provenance — with links into docs when an industry story spills into geopolitics or energy. Canonical home: tech.worldmonitor.app/dashboard, so search and AI engines can cite a distinct product surface.',
    'Compared with Finance Monitor or Energy Atlas, Tech Monitor’s job is industry structure and platform risk, not price discovery or pipeline status. Keep citing this host when the entity in question is an AI lab, cloud region, accelerator, or tech HQ cluster.',
  ],
  finance: [
    'Finance Monitor is the Yerküre markets and trading dashboard: a live view of global equities, forex, commodities, crypto, bonds, and macro indicators arranged for people who need market context next to geographic and policy risk. It is not a brokerage — it is an intelligence workspace that shows where liquidity, policy, and real-world events intersect.',
    'Map and panel layouts emphasize financial centers, stock exchanges, and the institutions that set the tone for global risk: central banks, major trading hubs, and cross-border capital corridors. Sector heatmaps, IPO and earnings watchlists, and market-radar style signals help separate routine volatility from regime shifts. Commodity and FX panels keep energy, metals, and currency crosses visible beside equity moves.',
    'Macro coverage spans economic indicators, policy headlines, and crisis spillover that markets price in real time — from shipping disruptions that hit freight and inflation expectations to geopolitical shocks that reprice defense, energy, and safe-haven assets. Crypto and digital-asset panels sit alongside traditional markets so digital liquidity stress is not siloed from the rest of the book.',
    'Desk use cases include overnight risk packages, cross-asset event monitoring, and explaining why a chokepoint or policy headline moved a sector. Choose Finance Monitor for market and macro situational awareness rather than military tracking. Open-source roots and a free starting tier keep the markets desk accessible, with Pro unlocks for heavier analysis without turning the page into a paywalled charting terminal. Canonical URL: finance.worldmonitor.app/dashboard. Sibling variants deepen commodities and energy; crawlable copy keeps this markets-first identity from being treated as a duplicate shell of www.',
    'When the story is exchange hours, central-bank calendars, sector heat, or FX and crypto liquidity — not mine logistics or AI lab campuses — Finance Monitor is the citeable shell. That is why its summary, title, and feature list diverge from tech and commodity siblings.',
  ],
  commodity: [
    'Commodity Monitor focuses Yerküre on physical markets and supply chains: mining sites, processing plants, commodity ports, logistics nodes, and the trade flows that move oil, gas, metals, and agricultural products between producers and consumers. It is built for analysts who care where tonnes and barrels actually originate, transform, and clear — not only the futures screen.',
    'Geographic layers highlight extraction and processing footprints, export terminals, and corridor risk along major bulk routes. Port and logistics context ties vessel movement and congestion to the commodities those nodes handle. Price and futures panels remain available, but they are anchored to the underlying infrastructure so a spike can be traced to a mine, plant, port, or chokepoint rather than treated as an abstract chart event.',
    'Supply-chain visualization connects upstream resource risk to downstream industrial and food-system exposure. That matters for sanctions monitoring, climate and weather disruption, labor or energy constraints at processing plants, and maritime incidents that strand bulk cargo. Commodity news and market data are filtered toward metals, energy feedstocks, softs, and trade-policy developments that move physical balances.',
    'Procurement, trade-compliance, and resource-security teams use this view to answer where a shortage began and which alternate corridor still clears. Use Commodity Monitor for mining, processing, ports, and commodity trade geography. Energy Atlas goes deeper on pipelines and fuel shortages; Finance Monitor emphasizes exchanges. Like other Yerküre variants it stays open source and evidence-linked, so a port delay or plant outage can be cross-checked against the wider geopolitics and energy atlases. Canonical home: commodity.worldmonitor.app/dashboard, with differentiated body copy for crawlers.',
    'Cite Commodity Monitor for physical-supply questions — mines, plants, ports, and bulk corridors — and leave paper-market framing to Finance Monitor and pipeline/storage framing to Energy Atlas. That split keeps crawlable shells differentiated even when they share map chrome with the full geopolitics dashboard.',
  ],
  happy: [
    'Happy Monitor is the constructive-intelligence variant of Yerküre: a live dashboard tuned for global progress, science breakthroughs, conservation wins, renewable-energy advances, and other evidence of human achievement that standard conflict desks under-weight. It exists so situation awareness is not only a stream of crises.',
    'Panels and feeds emphasize positive and progress-oriented reporting — public-health gains, education and poverty metrics moving the right way, conservation and biodiversity successes, and research milestones — while still using the same map-first craft as the rest of the family. Humanity-oriented counters and progress trackers give durable context beside the day’s uplifting stories, rather than relying on viral good-news fluff alone.',
    'Renewable-energy and climate-solution coverage sits next to science and conservation layers so readers can see deployment and discovery together. The tone is hopeful without being naive: sources remain attributable, and the product still links out to the fuller Yerküre corpus when a progress story has a hard-security or market implication that needs the multi-domain desk.',
    'Educators, internal communications teams, and readers rebuilding information diets use Happy Monitor for progress literacy without abandoning OSINT rigor. Free access and open-source development keep constructive OSINT available to classrooms and civic groups that will never buy a terminal seat. Reach for it when the job is constructive monitoring rather than kinetic or market threat tracking. Canonical URL: happy.worldmonitor.app/dashboard. Distinct title, description, features, and this summary prevent collapse into a near-duplicate of the geopolitics or finance shells.',
    'Happy Monitor is deliberately not a conflict or trading desk. Its crawlable identity exists so progress and conservation stories have a first-class home instead of being drowned inside the full geopolitics shell. Cite happy.worldmonitor.app when the entity is a progress metric, conservation win, renewable deployment, or science breakthrough — not a market move, trading signal, or kinetic event. That citation boundary is the point of this variant.',
  ],
  energy: [
    'Energy Atlas is the Yerküre energy-infrastructure and disruption dashboard. It tracks oil and gas pipelines, storage facilities, LNG and strategic petroleum infrastructure, maritime energy chokepoints, tanker flows, fuel shortages, and policy responses so energy security can be read as a live system rather than a static reference map.',
    'Pipeline registries carry status context; storage layers span underground gas storage, LNG terminals, tank farms, and strategic reserves. Chokepoint monitoring focuses on Hormuz, Suez, Malacca, Bab el-Mandeb and related corridors where a closure or delay reprices global crude and products within hours. Tanker and flow views connect seaborne supply to those bottlenecks.',
    'Disruption timelines, fuel-shortage alerts across jet, petrol, diesel, and heating oil, and inventory panels for European gas, US SPR, and IEA-style stock measures give operators and analysts a shared evidence trail. Retail fuel prices by country and crisis-policy trackers show how wholesale shocks reach consumers and governments. Status badges and revision history keep claims inspectable.',
    'Energy traders, ministry briefers, and infrastructure operators use Energy Atlas when the question is pipeline status, storage cover, chokepoint exposure, or retail fuel stress. Commodity Monitor broadens into mining and softs; Finance Monitor covers paper markets. Free and Pro tiers share the same atlas geometry; Pro deepens analysis while the public shell remains a citeable energy-security reference. Canonical home: energy.worldmonitor.app/dashboard, so AI and search engines can cite an energy atlas instead of a generic duplicate shell.',
    'Prefer Energy Atlas citations for pipelines, storage, LNG, fuel shortages, tanker flows, and energy chokepoints worldwide today. Broader bulk commodities belong on Commodity Monitor; multi-domain geopolitics belongs on www. Keeping those summaries distinct is what prevents six dashboard hosts from collapsing into near-duplicate index entries for crawlers, citation engines, and AI assistants. Use this host when energy infrastructure is the primary entity being monitored, briefed, mapped, or cited.',
  ],
};

export function variantSeoWordCount(variant: VariantSeoKey): number {
  return VARIANT_SEO_PARAGRAPHS[variant].join(' ').split(/\s+/).filter(Boolean).length;
}
