/**
 * Curated geographic reference data: intelligence hotspots, conflict zones and
 * strategic waterways.
 *
 * This lives in `shared/` because both the browser dashboard (via
 * `src/config/geo.ts`) and server-side Edge/MCP handlers need it. Top-level
 * `shared/` modules are imported from code where `src/` imports are forbidden
 * (scripts/lint-boundaries.mjs), so the structural types below are declared
 * here instead of imported from `@/types`. They mirror the client-facing
 * interfaces in `src/types/index.ts` field for field, which is what lets
 * `src/config/geo.ts` re-export these arrays as the client types.
 */

export type EscalationTrend = 'escalating' | 'stable' | 'de-escalating';

export interface HistoricalContext {
  lastMajorEvent?: string;
  lastMajorEventDate?: string;
  precedentCount?: number;
  precedentDescription?: string;
  cyclicalRisk?: string;
}

export interface Hotspot {
  id: string;
  name: string;
  lat: number;
  lon: number;
  keywords: string[];
  subtext?: string;
  location?: string;
  agencies?: string[];
  level?: 'low' | 'elevated' | 'high';
  description?: string;
  status?: string;
  escalationScore?: 1 | 2 | 3 | 4 | 5;
  escalationTrend?: EscalationTrend;
  escalationIndicators?: string[];
  history?: HistoricalContext;
  whyItMatters?: string;
}

export interface StrategicWaterway {
  id: string;
  /** Canonical chokepoint ID from chokepoint-registry.ts — same as id. */
  chokepointId: string;
  name: string;
  lat: number;
  lon: number;
  description?: string;
}

export interface ConflictZone {
  id: string;
  name: string;
  coords: [number, number][];
  center: [number, number];
  intensity?: 'high' | 'medium' | 'low';
  parties?: string[];
  casualties?: string;
  displaced?: string;
  keywords?: string[];
  startDate?: string;
  location?: string;
  description?: string;
  keyDevelopments?: string[];
  peaceAgreements?: string[];
  totalFatalities?: string;
}

// Hotspot levels are NOT hardcoded - they are dynamically calculated based on news activity
// All hotspots start at 'low' and rise to 'elevated' or 'high' based on matching news items
// Escalation scores: 1=stable, 2=watchlist, 3=elevated, 4=high tension, 5=critical/active conflict
export const INTEL_HOTSPOTS: Hotspot[] = [
  {
    id: 'sahel',
    name: 'Sahel',
    subtext: 'Insurgency/Coups',
    lat: 14.0,
    lon: -1.0,
    location: 'Sahel Region (Mali, Burkina Faso, Niger)',
    keywords: ['burkina faso', 'mali', 'niger', 'sahel', 'junta', 'coup', 'wagner', 'africa corps'],
    agencies: ['Wagner', 'Junta Forces'],
    description: 'Region of instability, military coups, and Islamist insurgency. Russian influence growing.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['4 coups since 2020', 'French forces expelled', 'Wagner/Africa Corps expansion', 'ECOWAS sanctions'],
    history: {
      lastMajorEvent: 'Niger coup',
      lastMajorEventDate: '2023-07-26',
      precedentCount: 4,
      precedentDescription: '4 military coups in 3 years (Mali 2020/2021, Burkina Faso 2022, Niger 2023)',
      cyclicalRisk: 'Dry season offensives (Oct-May)',
    },
    whyItMatters: 'Russian influence expanding in former French sphere; jihadist groups gaining territory; migration pressure on Europe',
  },
  {
    id: 'haiti',
    name: 'Port-au-Prince',
    subtext: 'Haiti Crisis',
    lat: 18.5,
    lon: -72.3,
    location: 'Haiti, Caribbean',
    keywords: ['haiti', 'port-au-prince', 'gangs', 'kenya mission', 'barbecue'],
    agencies: ['UN', 'HNP', 'Kenya Police'],
    description: 'Gang violence, government collapse, international security mission.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'stable',
    escalationIndicators: ['Gangs control 80% of capital', 'PM resigned under pressure', 'Kenya-led mission deployed', 'Mass displacement'],
    history: {
      lastMajorEvent: 'PM Henry resignation',
      lastMajorEventDate: '2024-03-11',
      precedentCount: 3,
      precedentDescription: 'Repeated state collapse (2004 Aristide, 2021 Moïse assassination, 2024 gang takeover)',
      cyclicalRisk: 'Hurricane season vulnerability (Jun-Nov)',
    },
    whyItMatters: 'Humanitarian catastrophe at US doorstep; migration surge potential; test of African-led peacekeeping',
  },
  {
    id: 'horn_africa',
    name: 'Horn of Africa',
    subtext: 'Piracy/Conflict',
    lat: 10.0,
    lon: 49.0,
    location: 'Somalia, Ethiopia, Djibouti',
    keywords: ['somalia', 'piracy', 'al-shabaab', 'ethiopia', 'somaliland', 'red sea'],
    agencies: ['USAFRICOM', 'EUNAVFOR'],
    description: 'Resurgent piracy, Al-Shabaab activity, Ethiopia-Somaliland port dispute.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Houthi attacks on shipping', 'Somali piracy resurgence', 'Ethiopia-Somaliland MoU dispute', 'Sudan civil war spillover'],
    history: {
      lastMajorEvent: 'Sudan war outbreak',
      lastMajorEventDate: '2023-04-15',
      precedentCount: 5,
      precedentDescription: 'Ethiopia-Eritrea war, Tigray war, Somali civil war, Sudan coups, piracy waves',
      cyclicalRisk: 'Monsoon affects naval operations (Jun-Sep)',
    },
    whyItMatters: 'Bab el-Mandeb chokepoint security; 12% of global trade at risk; Red Sea shipping rerouting',
  },
  {
    id: 'pak_afghan',
    name: 'Pakistan–Afghanistan Border',
    subtext: 'Border Conflict / TTP',
    lat: 31.8,
    lon: 69.0,
    location: 'Pakistan–Afghanistan border (KP, Balochistan)',
    keywords: ['pakistan', 'afghanistan', 'ttp', 'taliban', 'torkham', 'chaman', 'waziristan', 'khyber', 'peshawar', 'border', 'cross-border', 'airstrike', 'pak-afghan'],
    agencies: ['Pakistan Military', 'TTP', 'Afghan Taliban'],
    description: 'Ongoing conflict along the Pak–Afghan border. Pakistan military operations against TTP; cross-border strikes and border closures. Tensions with Afghan Taliban over border security.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Border clashes and closures', 'Pakistan airstrikes in Afghanistan', 'TTP attacks in KP', 'Torkham/Chaman crossing tensions'],
    history: {
      lastMajorEvent: 'Cross-border strikes and border closures',
      lastMajorEventDate: '2024',
      precedentCount: 3,
      precedentDescription: 'Recurring border crises, TTP resurgence post-2021, militant sanctuaries in Afghanistan',
      cyclicalRisk: 'Militant infiltration; seasonal operations',
    },
    whyItMatters: 'Nuclear-armed state at contested border; regional stability; displacement and humanitarian impact',
  },
  {
    id: 'dc',
    name: 'DC',
    subtext: 'Pentagon Pizza Index',
    lat: 38.9,
    lon: -77.0,
    location: 'Washington D.C., USA',
    keywords: ['pentagon', 'white house', 'congress', 'cia', 'nsa', 'washington', 'biden', 'trump', 'senate', 'supreme court', 'vance', 'elon'],
    agencies: ['Pentagon', 'CIA', 'NSA', 'State Dept'],
    description: 'US government and military headquarters. Intelligence community center.',
    status: 'Monitoring',
  },
  {
    id: 'silicon_valley',
    name: 'Silicon Valley',
    subtext: 'Tech/AI Hub',
    lat: 37.4,
    lon: -122.1,
    location: 'California, USA',
    keywords: ['google', 'apple', 'meta', 'nvidia', 'openai', 'anthropic', 'silicon valley', 'san francisco', 'palo alto', 'tech layoffs', 'ai', 'artificial intelligence'],
    agencies: ['Big Tech', 'AI Labs', 'VC'],
    description: 'Global tech center. AI development hub. Major economic indicator.',
    status: 'Monitoring',
  },
  {
    id: 'wall_street',
    name: 'Wall Street',
    subtext: 'Financial Hub',
    lat: 40.7,
    lon: -74.0,
    location: 'New York City, USA',
    keywords: ['wall street', 'fed', 'federal reserve', 'nyse', 'nasdaq', 'dow', 'sp500', 'stock market', 'goldman', 'jpmorgan', 'blackrock'],
    agencies: ['Fed', 'SEC', 'NYSE'],
    description: 'Global financial center. Market movements. Fed policy.',
    status: 'Monitoring',
  },
  {
    id: 'houston',
    name: 'Houston',
    subtext: 'Energy/Space',
    lat: 29.76,
    lon: -95.37,
    location: 'Texas, USA',
    keywords: ['houston', 'nasa', 'spacex', 'oil', 'energy', 'texas', 'exxon', 'chevron', 'lng'],
    agencies: ['NASA', 'Energy Corps'],
    description: 'Energy sector HQ. NASA mission control. Space industry.',
    status: 'Monitoring',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    subtext: 'Kremlin Activity',
    lat: 55.75,
    lon: 37.6,
    location: 'Russia',
    keywords: ['kremlin', 'putin', 'russia', 'fsb', 'moscow', 'russian'],
    agencies: ['Kremlin', 'FSB', 'GRU', 'SVR'],
    description: 'Russian Federation command center. Military operations hub.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'stable',
    escalationIndicators: ['Ukraine war ongoing', 'Mobilization potential', 'Nuclear rhetoric', 'Wagner aftermath'],
    history: {
      lastMajorEvent: 'Wagner mutiny',
      lastMajorEventDate: '2023-06-24',
      precedentCount: 2,
      precedentDescription: 'Crimea annexation 2014, Ukraine invasion 2022',
      cyclicalRisk: 'Victory Day (May 9) speeches, Putin addresses',
    },
    whyItMatters: 'Nuclear power at war; energy leverage over Europe; global order revisionism',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    subtext: 'PLA/MSS Activity',
    lat: 39.9,
    lon: 116.4,
    location: 'China',
    keywords: ['beijing', 'xi', 'china', 'pla', 'ccp', 'chinese', 'jinping'],
    agencies: ['PLA', 'MSS', 'CCP Politburo'],
    description: 'Chinese Communist Party headquarters. PLA command center.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['Taiwan Strait exercises', 'South China Sea militarization', 'Tech decoupling', 'Xi third term'],
    history: {
      lastMajorEvent: 'Xi unprecedented third term',
      lastMajorEventDate: '2022-10-22',
      precedentCount: 3,
      precedentDescription: 'Tiananmen 1989, Hong Kong crackdown 2020, COVID lockdowns 2022',
      cyclicalRisk: 'Party Congress (every 5 years), Tiananmen anniversary (June 4)',
    },
    whyItMatters: 'Largest economy by PPP; primary US strategic competitor; Taiwan contingency risk',
  },
  {
    id: 'kyiv',
    name: 'Kyiv',
    subtext: 'Conflict Zone',
    lat: 50.45,
    lon: 30.5,
    location: 'Ukraine',
    keywords: ['kyiv', 'ukraine', 'zelensky', 'ukrainian', 'kiev'],
    agencies: ['Ukrainian Armed Forces', 'SBU'],
    description: 'Active conflict zone. NATO support operations.',
    status: 'Monitoring',
    escalationScore: 5,
    escalationTrend: 'stable',
    escalationIndicators: ['Active combat operations', 'Western weapons deliveries', 'Drone warfare escalation', 'Nuclear plant risks'],
    history: {
      lastMajorEvent: 'Russian full invasion',
      lastMajorEventDate: '2022-02-24',
      precedentCount: 2,
      precedentDescription: 'Crimea annexation 2014, Donbas war 2014-2022',
      cyclicalRisk: 'Spring/summer offensive season, Winter energy attacks',
    },
    whyItMatters: 'Largest European war since WWII; NATO Article 5 test; global food/energy security',
  },
  {
    id: 'taipei',
    name: 'Taipei',
    subtext: 'Strait Watch',
    lat: 25.03,
    lon: 121.5,
    location: 'Taiwan',
    keywords: ['taiwan', 'taipei', 'tsmc', 'strait', 'taiwanese'],
    agencies: ['ROC Military', 'TSMC'],
    description: 'Taiwan Strait tensions. Semiconductor supply chain.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['PLA exercises around Taiwan', 'US arms sales', 'TSMC Arizona fab', 'DPP governance'],
    history: {
      lastMajorEvent: 'Pelosi Taiwan visit',
      lastMajorEventDate: '2022-08-02',
      precedentCount: 3,
      precedentDescription: '1954-55 Strait Crisis, 1995-96 missile crisis, 2022 exercises',
      cyclicalRisk: 'US-Taiwan political visits, PRC National Day (Oct 1)',
    },
    whyItMatters: 'TSMC produces 90% of advanced chips; conflict would devastate global tech supply chains',
  },
  {
    id: 'tehran',
    name: 'Tehran',
    subtext: 'IRGC Activity',
    lat: 35.7,
    lon: 51.4,
    location: 'Iran',
    keywords: ['iran', 'tehran', 'irgc', 'khamenei', 'persian', 'iranian'],
    agencies: ['IRGC', 'Quds Force', 'MOIS'],
    description: 'Iranian nuclear program. Regional proxy operations.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Near-weapons-grade enrichment', 'Proxy attacks on Israel', 'Houthi coordination', 'Succession uncertainty'],
    history: {
      lastMajorEvent: 'JCPOA collapse acceleration',
      lastMajorEventDate: '2023-01-01',
      precedentCount: 4,
      precedentDescription: 'Revolution 1979, Iran-Iraq War, JCPOA negotiations, Soleimani assassination',
      cyclicalRisk: 'Quds Day (annually), Khamenei health status',
    },
    whyItMatters: 'Near-nuclear threshold state; controls Strait of Hormuz; Axis of Resistance coordinator',
  },
  {
    id: 'telaviv',
    name: 'Tel Aviv',
    subtext: 'Mossad/IDF',
    lat: 32.1,
    lon: 34.8,
    location: 'Israel',
    keywords: ['israel', 'idf', 'mossad', 'gaza', 'netanyahu', 'israeli', 'hamas', 'hezbollah'],
    agencies: ['IDF', 'Mossad', 'Shin Bet'],
    description: 'Military operations. Regional security. Intelligence activities.',
    status: 'Monitoring',
    escalationScore: 5,
    escalationTrend: 'stable',
    escalationIndicators: ['Gaza operations ongoing', 'Hezbollah northern front', 'Iran shadow war', 'Judicial crisis paused'],
    history: {
      lastMajorEvent: 'October 7 attacks',
      lastMajorEventDate: '2023-10-07',
      precedentCount: 5,
      precedentDescription: '1948 War, 1967 Six-Day War, 1973 Yom Kippur, Lebanon 2006, Gaza wars',
      cyclicalRisk: 'Jewish holidays, Ramadan tensions, election cycles',
    },
    whyItMatters: 'Regional escalation risk to multi-front war; US treaty ally; Iran confrontation flashpoint',
  },
  {
    id: 'pyongyang',
    name: 'Pyongyang',
    subtext: 'DPRK Watch',
    lat: 39.0,
    lon: 125.75,
    location: 'North Korea',
    keywords: ['north korea', 'kim', 'pyongyang', 'dprk', 'korean'],
    agencies: ['KPA', 'RGB', 'Lazarus Group'],
    description: 'Nuclear weapons program. Missile testing. Cyber operations.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['ICBM testing resumed', 'Russia arms cooperation', 'Satellite launches', 'Constitution change on ROK'],
    history: {
      lastMajorEvent: 'Hwasong-18 ICBM test',
      lastMajorEventDate: '2023-12-18',
      precedentCount: 4,
      precedentDescription: 'Korean War 1950-53, nuclear tests 2006-2017, Trump summits, missile tests ongoing',
      cyclicalRisk: 'Kim Il-sung birthday (April 15), party anniversaries',
    },
    whyItMatters: 'Nuclear-armed hermit state; ICBM can reach US mainland; cyber threat actor; Russia military supplier',
  },
  {
    id: 'london',
    name: 'London',
    subtext: 'GCHQ/MI6',
    lat: 51.5,
    lon: -0.12,
    location: 'United Kingdom',
    keywords: ['london', 'uk', 'britain', 'gchq', 'mi6', 'british'],
    agencies: ['MI6', 'GCHQ', 'MI5'],
    description: 'UK intelligence headquarters. Five Eyes member.',
    status: 'Monitoring',
  },
  {
    id: 'brussels',
    name: 'Brussels',
    subtext: 'NATO HQ',
    lat: 50.85,
    lon: 4.35,
    location: 'Belgium (NATO HQ)',
    keywords: ['nato', 'brussels', 'eu', 'european union', 'europe'],
    agencies: ['NATO', 'EU Commission'],
    description: 'NATO alliance headquarters. European Union center.',
    status: 'Monitoring',
  },
  {
    id: 'caracas',
    name: 'Caracas',
    subtext: 'Venezuela Crisis',
    lat: 10.5,
    lon: -66.9,
    location: 'Venezuela',
    keywords: ['venezuela', 'maduro', 'caracas', 'venezuelan'],
    agencies: ['Maduro Govt', 'SEBIN'],
    description: 'Political crisis. Economic sanctions. Regional instability.',
    status: 'Monitoring',
  },
  {
    id: 'mexico',
    name: 'Mexico City',
    subtext: 'Cartel Violence',
    lat: 23.6,
    lon: -102.5,
    location: 'Mexico',
    keywords: ['mexico', 'cartel', 'sinaloa', 'jalisco', 'narco', 'cjng', 'fentanyl', 'el chapo', 'national guard mexico', 'zetas', 'michoacan', 'juarez', 'tijuana', 'border violence', 'mexican army', 'sedena', 'extradition mexico'],
    agencies: ['Sedena', 'National Guard', 'DEA', 'FGR'],
    description: 'Cartel warfare, fentanyl trafficking, military deployments, state fragility in multiple regions.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Sinaloa cartel fragmentation', 'CJNG territorial expansion', 'Military deployed to multiple states', 'Record fentanyl seizures', 'Prison breaks and gang violence'],
    history: {
      lastMajorEvent: 'Sinaloa cartel leadership crisis',
      lastMajorEventDate: '2024-07-25',
      precedentCount: 5,
      precedentDescription: 'Decades of cartel wars (Sinaloa vs CJNG, Zetas era, Calderón drug war 2006, El Chapo captures)',
      cyclicalRisk: 'Election cycles trigger violence; cartel leadership changes spark turf wars',
    },
    whyItMatters: 'Largest US land border; fentanyl crisis killing 100k+ Americans/year; regional destabilization; migration driver',
  },
  {
    id: 'nuuk',
    name: 'Nuuk',
    subtext: 'Greenland Intel',
    lat: 64.18,
    lon: -51.7,
    location: 'Greenland (Denmark)',
    keywords: ['greenland', 'nuuk', 'arctic', 'denmark', 'danish'],
    agencies: ['Danish Defence', 'US Space Force', 'Arctic Council'],
    description: 'Arctic strategic territory. US military presence, sovereignty questions.',
    status: 'Monitoring',
  },
  // Middle East hotspots
  {
    id: 'riyadh',
    name: 'Riyadh',
    subtext: 'Saudi GIP/MBS',
    lat: 24.7,
    lon: 46.7,
    location: 'Saudi Arabia',
    keywords: ['saudi', 'riyadh', 'mbs', 'aramco', 'opec', 'saudi arabia'],
    agencies: ['GIP', 'Saudi Royal Court', 'Aramco'],
    description: 'Saudi Arabia power center. OPEC+ decisions. Regional influence.',
    status: 'Monitoring',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    subtext: 'Egypt/GIS',
    lat: 30.0,
    lon: 31.2,
    location: 'Egypt',
    keywords: ['egypt', 'cairo', 'sisi', 'egyptian', 'suez'],
    agencies: ['GIS', 'Egyptian Armed Forces'],
    description: 'Egyptian command. Gaza border control. Suez Canal security.',
    status: 'Monitoring',
  },
  {
    id: 'baghdad',
    name: 'Baghdad',
    subtext: 'Iraq/PMF',
    lat: 33.3,
    lon: 44.4,
    location: 'Iraq',
    keywords: ['iraq', 'baghdad', 'iraqi', 'pmf', 'militia'],
    agencies: ['Iraqi Security Forces', 'PMF', 'US Embassy'],
    description: 'Iraqi government. Iran-backed militias. US military presence.',
    status: 'Monitoring',
  },
  {
    id: 'damascus',
    name: 'Damascus',
    subtext: 'Syria Crisis',
    lat: 33.5,
    lon: 36.3,
    location: 'Syria',
    keywords: ['syria', 'damascus', 'assad', 'syrian', 'hts'],
    agencies: ['Syrian Govt', 'HTS', 'Russian Forces', 'Turkish Forces'],
    description: 'Syrian civil war aftermath. Multiple foreign interventions.',
    status: 'Monitoring',
  },
  {
    id: 'doha',
    name: 'Doha',
    subtext: 'Qatar/Al Udeid',
    lat: 25.3,
    lon: 51.5,
    location: 'Qatar',
    keywords: ['qatar', 'doha', 'qatari', 'al jazeera'],
    agencies: ['Qatari State Security', 'CENTCOM Forward HQ'],
    description: 'Qatar diplomatic hub. US CENTCOM base. Al Jazeera HQ.',
    status: 'Monitoring',
  },
  {
    id: 'ankara',
    name: 'Ankara',
    subtext: 'Turkey/MIT',
    lat: 39.9,
    lon: 32.9,
    location: 'Turkey',
    keywords: ['turkey', 'ankara', 'erdogan', 'turkish', 'mit'],
    agencies: ['MIT', 'Turkish Armed Forces', 'AKP'],
    description: 'NATO member. Kurdish conflict. Syria/Libya operations.',
    status: 'Monitoring',
  },
  {
    id: 'beirut',
    name: 'Beirut',
    subtext: 'Lebanon/Hezbollah',
    lat: 33.9,
    lon: 35.5,
    location: 'Lebanon',
    keywords: ['lebanon', 'beirut', 'hezbollah', 'lebanese', 'nasrallah'],
    agencies: ['LAF', 'Hezbollah', 'UNIFIL'],
    description: 'Lebanon crisis. Hezbollah stronghold. Israel border tensions.',
    status: 'Monitoring',
  },
  {
    id: 'sanaa',
    name: "Sana'a",
    subtext: 'Yemen/Houthis',
    lat: 15.4,
    lon: 44.2,
    keywords: ['yemen', 'houthi', 'sanaa', 'yemeni', 'red sea'],
    agencies: ['Houthi Forces', 'Saudi Coalition', 'US Navy'],
    description: 'Yemen conflict. Houthi Red Sea attacks. Shipping disruption.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Red Sea shipping attacks', 'US/UK strikes on Yemen', 'Iran weapon supplies', 'Commercial ship seizures'],
    history: {
      lastMajorEvent: 'Red Sea campaign begins',
      lastMajorEventDate: '2023-11-19',
      precedentCount: 3,
      precedentDescription: 'Civil war since 2014, Saudi intervention 2015, US strikes 2024',
      cyclicalRisk: 'Ramadan, Gaza war linkage',
    },
    whyItMatters: 'Disrupting 12% of global trade via Suez; insurance costs spiking; Iran proxy demonstration',
  },
  {
    id: 'abudhabi',
    name: 'Abu Dhabi',
    subtext: 'UAE/ECSR',
    lat: 24.5,
    lon: 54.4,
    keywords: ['uae', 'abu dhabi', 'emirates', 'emirati', 'dubai'],
    agencies: ['ECSR', 'UAE Armed Forces'],
    description: 'UAE strategic hub. Regional military operations.',
    status: 'Monitoring',
  },
];

export const STRATEGIC_WATERWAYS: StrategicWaterway[] = [
  { id: 'taiwan_strait',    chokepointId: 'taiwan_strait',    name: 'TAIWAN STRAIT',      lat: 24.0,   lon: 119.5,  description: 'Critical shipping lane, PLA activity' },
  { id: 'malacca_strait',   chokepointId: 'malacca_strait',   name: 'MALACCA STRAIT',     lat: 2.5,    lon: 101.5,  description: 'Major oil shipping route' },
  { id: 'hormuz_strait',    chokepointId: 'hormuz_strait',    name: 'STRAIT OF HORMUZ',   lat: 26.5,   lon: 56.5,   description: 'Oil chokepoint, Iran control' },
  { id: 'bosphorus',        chokepointId: 'bosphorus',        name: 'BOSPHORUS STRAIT',   lat: 41.1,   lon: 29.0,   description: 'Black Sea access, Turkey control' },
  { id: 'suez',             chokepointId: 'suez',             name: 'SUEZ CANAL',         lat: 30.5,   lon: 32.3,   description: 'Europe-Asia shipping' },
  { id: 'panama',           chokepointId: 'panama',           name: 'PANAMA CANAL',       lat: 9.1,    lon: -79.7,  description: 'Americas shipping route' },
  { id: 'gibraltar',        chokepointId: 'gibraltar',        name: 'STRAIT OF GIBRALTAR',lat: 35.9,   lon: -5.6,   description: 'Mediterranean access, NATO control' },
  { id: 'bab_el_mandeb',    chokepointId: 'bab_el_mandeb',    name: 'BAB EL-MANDEB',      lat: 12.5,   lon: 43.3,   description: 'Red Sea chokepoint, Houthi attacks' },
  { id: 'cape_of_good_hope',chokepointId: 'cape_of_good_hope',name: 'CAPE OF GOOD HOPE',  lat: -34.36, lon: 18.49,  description: 'Suez bypass route, tanker traffic' },
  { id: 'dover_strait',     chokepointId: 'dover_strait',     name: 'DOVER STRAIT',       lat: 51.0,   lon: 1.5,    description: 'English Channel narrows, busiest shipping lane' },
  { id: 'korea_strait',     chokepointId: 'korea_strait',     name: 'KOREA STRAIT',       lat: 34.0,   lon: 129.0,  description: 'Japan-Korea shipping lane' },
  { id: 'kerch_strait',     chokepointId: 'kerch_strait',     name: 'KERCH STRAIT',       lat: 45.3,   lon: 36.6,   description: 'Black Sea-Azov access, Russia-Ukraine flashpoint' },
  { id: 'lombok_strait',    chokepointId: 'lombok_strait',    name: 'LOMBOK STRAIT',      lat: -8.5,   lon: 115.7,  description: 'Malacca bypass for deep-draft vessels' },
];


export const CONFLICT_ZONES: ConflictZone[] = [
  {
    id: 'iran',
    name: 'Iran War Theater',
    coords: [[44, 39.7], [46, 39.5], [48.5, 38.5], [50.5, 37.5], [53.5, 37.5], [55.5, 38], [57, 37.5], [58.5, 37.5], [61, 36.5], [63.5, 35.5], [63.5, 31.5], [62.5, 29.5], [61, 28], [59, 26.5], [57.5, 25.5], [56.5, 25.5], [55, 26.5], [54, 27], [52.5, 27.5], [50.5, 28.5], [49, 29.5], [47.5, 30], [46, 31.5], [45.5, 33.5], [45.8, 35.5], [46.5, 37], [44, 38.5], [44, 39.7]],
    center: [53, 32],
    intensity: 'high',
    parties: ['United States', 'Israel', 'Iran', 'IRGC'],
    casualties: '200+ killed (first 72hrs)',
    displaced: 'Millions fleeing major cities',
    keywords: ['iran', 'tehran', 'khamenei', 'epic fury', 'roaring lion', 'irgc', 'centcom', 'isfahan', 'bushehr'],
    startDate: 'Feb 28, 2026',
    location: 'Iran (nationwide)',
    description: 'Joint US-Israeli military operation (US: Operation Epic Fury / Israel: Operation Roaring Lion). 1000+ targets struck including military, nuclear, and leadership sites. Supreme Leader Khamenei killed in Tehran strikes. Iran retaliating with missiles and drones across the region.',
    keyDevelopments: ['Khamenei killed in Tehran strikes', '1000+ Iranian targets struck', '3 US service members KIA', 'Iranian missile/drone retaliation on Gulf states'],
  },
  {
    id: 'strait_hormuz',
    name: 'Strait of Hormuz Crisis',
    coords: [[54.5, 25.5], [55.5, 25], [57, 24.8], [58.5, 25], [58.5, 26.8], [57.5, 27.5], [56, 27.5], [54.5, 27], [54.5, 25.5]],
    center: [56.5, 26.2],
    intensity: 'high',
    parties: ['Iran (IRGC Navy)', 'US Navy (5th Fleet)', 'Coalition forces'],
    casualties: 'Maritime casualties reported',
    displaced: 'Global shipping halted',
    keywords: ['hormuz', 'strait', 'persian gulf', 'shipping', 'tanker', 'oil', 'blockade', 'navy'],
    startDate: 'Feb 28, 2026',
    location: 'Strait of Hormuz & Persian Gulf Approaches',
    description: 'Iran attempting to close Strait of Hormuz. IRGC naval/air operations active. Three tankers damaged. US sank 9 Iranian warships. GPS spoofing/jamming reported. 20-30% of global oil/gas transits through this chokepoint. Brent crude spiking to $80+.',
    keyDevelopments: ['Iran attempts Hormuz closure', '3 tankers damaged', 'US sinks 9 Iranian warships', 'Global shipping paused', 'Oil prices spike'],
  },
  {
    id: 'ukraine',
    name: 'Ukraine War',
    coords: [[22.137, 48.09], [22.558, 49.085], [22.66, 49.79], [23.2, 50.38], [23.82, 51.22], [24.09, 51.89], [25.6, 51.93], [27.85, 52.18], [30.17, 52.1], [32.76, 52.32], [34.4, 51.76], [36.28, 50.3], [38.25, 49.92], [40.18, 49.6], [40.08, 48.88], [39.68, 47.77], [38.21, 47.1], [36.65, 46.58], [35.19, 46.1], [36.47, 45.22], [36, 44.4], [33.55, 44.39], [32.48, 44.52], [31.78, 45.2], [31.44, 46.03], [30.76, 46.38], [29.6, 45.38], [28.21, 45.45], [28.68, 46.45], [28.24, 47.11], [26.62, 48.26], [24.58, 47.96], [22.87, 47.95], [22.137, 48.09]],
    center: [31, 48.5],
    intensity: 'high',
    parties: ['Russia', 'Ukraine', 'NATO (support)'],
    casualties: '500,000+ (est.)',
    displaced: '6.5M+ refugees',
    keywords: ['ukraine', 'russia', 'zelensky', 'putin', 'donbas', 'crimea'],
    startDate: 'Feb 24, 2022',
    location: 'Eastern Ukraine (Donetsk, Luhansk)',
    description: 'Full-scale Russian invasion of Ukraine. Active frontlines in Donetsk, Luhansk, Zaporizhzhia, and Kherson oblasts. Heavy artillery, drone warfare, and trench combat.',
    keyDevelopments: ['Battle of Bakhmut', 'Kursk incursion', 'Black Sea drone strikes', 'Infrastructure attacks'],
    peaceAgreements: ['Minsk I (2014, failed)', 'Minsk II (2015, failed)'],
    totalFatalities: '500,000+',
  },
  {
    id: 'gaza',
    name: 'Gaza Conflict',
    coords: [[34, 32], [35, 32], [35, 31], [34, 31]],
    center: [34.5, 31.5],
    intensity: 'high',
    parties: ['Israel', 'Hamas', 'Hezbollah', 'PIJ'],
    casualties: '40,000+ (Gaza)',
    displaced: '2M+ displaced',
    keywords: ['gaza', 'israel', 'hamas', 'palestinian'],
    startDate: 'Oct 7, 2023',
    location: 'Gaza Strip, Palestinian Territories',
    description: 'Israeli military operations in Gaza following October 7 attacks. Ground invasion, aerial bombardment. Humanitarian crisis. Regional escalation with Hezbollah.',
    keyDevelopments: ['Rafah ground operation', 'Humanitarian crisis', 'Hostage negotiations', 'Iran-backed attacks'],
    peaceAgreements: ['Oslo Accords (1993, undermined)'],
    totalFatalities: '40,000+',
  },
  {
    id: 'south_lebanon',
    name: 'Israel-Lebanon Border',
    coords: [[35.1, 33.0], [35.1, 33.4], [35.8, 33.4], [35.8, 33.0]],
    center: [35.4, 33.2],
    intensity: 'high',
    parties: ['Israel (IDF)', 'Hezbollah'],
    casualties: '500+ killed',
    displaced: '150k+ displaced',
    keywords: ['hezbollah', 'lebanon', 'israel', 'border', 'rocket', 'airstrike'],
    startDate: 'Oct 8, 2023',
    location: 'Southern Lebanon / Northern Israel',
    description: 'Cross-border artillery and rocket fire. Targeted assassinations. High risk of full-scale escalation.',
    keyDevelopments: ['Daily rocket fire', 'IDF airstrikes', 'Buffer zone evacuation', 'Litani River tensions'],
    peaceAgreements: ['UNSC Resolution 1701 (2006)'],
    totalFatalities: '1,500+',
  },
  {
    id: 'yemen_redsea',
    name: 'Red Sea Crisis',
    coords: [
      // NW coast along Red Sea
      [42.6, 16.5],
      [42.8, 15.8],
      [42.7, 15.2],
      [42.9, 14.8],
      [43.1, 14.0],
      // Bab el-Mandeb Strait
      [43.3, 12.6],
      [43.5, 12.4],
      // Gulf of Aden coast (south)
      [44.0, 12.6],
      [44.8, 12.5],
      [45.2, 12.8],
      [45.5, 13.0],
      [46.0, 13.4],
      [46.8, 13.8],
      [47.5, 13.9],
      [48.0, 14.0],
      [48.5, 14.5],
      [49.5, 14.7],
      [50.5, 14.9],
      [51.5, 14.7],
      [52.0, 15.0],
      [52.2, 15.6],
      // Inland boundary (north)
      [51.5, 16.0],
      [50.0, 16.4],
      [48.5, 16.8],
      [47.0, 17.0],
      [46.0, 17.2],
      [45.0, 17.0],
      [44.5, 17.0],
      [43.5, 17.0],
      // Close
      [42.6, 16.5],
    ],
    center: [46, 14.5],
    intensity: 'high',
    parties: ['Houthis', 'US/UK Coalition', 'Yemen Govt'],
    casualties: 'Unknown (Maritime)',
    displaced: '4.5M+ (Yemen Civil War)',
    keywords: ['houthi', 'red sea', 'yemen', 'missile', 'drone', 'ship'],
    startDate: 'Nov 19, 2023',
    location: 'Red Sea & Gulf of Aden, Yemen',
    description: 'Houthi maritime campaign against commercial shipping. US/UK airstrikes on Houthi targets. Ongoing blockade attempts.',
    keyDevelopments: ['Ship hijackings', 'US airstrikes', 'Cable cuts', 'Sinking of Rubymar'],
    peaceAgreements: ['Stockholm Agreement (2018, partial)'],
    totalFatalities: '150,000+ (Yemen Civil War)',
  },
  {
    id: 'sudan',
    name: 'Sudan Civil War',
    coords: [
      [21.8, 22.0], [24.0, 21.9], [31.4, 22.0], [33.2, 22.0],
      [36.9, 22.0], [36.9, 19.5], [37.5, 18.2], [38.6, 18.0],
      [38.5, 17.4], [37.0, 16.6], [36.5, 14.5], [35.3, 12.2],
      [34.1, 10.6], [33.2, 9.6], [32.0, 9.8], [30.2, 9.4],
      [29.0, 9.8], [27.5, 9.5], [25.0, 10.2], [24.0, 12.5],
      [23.5, 15.6], [22.0, 16.0], [21.8, 20.0], [21.8, 22.0],
    ],
    center: [30, 15.5],
    intensity: 'high',
    parties: ['Sudanese Armed Forces (SAF)', 'Rapid Support Forces (RSF)', 'Allied militias'],
    casualties: '150,000+ killed (est.)',
    displaced: '14M+ internally displaced, 3M+ refugees',
    keywords: ['sudan', 'khartoum', 'darfur', 'rsf', 'saf', 'el fasher', 'port sudan', 'wad madani', 'al jazirah', 'famine', 'hemedti'],
    startDate: 'Apr 15, 2023',
    location: 'Sudan (nationwide)',
    description: 'Power struggle between SAF and RSF paramilitary has engulfed the entire country. RSF controls most of Darfur and Khartoum; SAF holds Port Sudan and eastern regions. World\'s largest displacement crisis. Famine conditions in multiple states.',
    keyDevelopments: ['Khartoum destruction', 'Darfur ethnic massacres', 'El Fasher siege', 'Wad Madani fall to RSF', 'Famine declared in North Darfur', 'SAF counter-offensives', 'Regional proxy involvement (UAE, Egypt)'],
    totalFatalities: '150,000+',
  },
  {
    id: 'myanmar',
    name: 'Myanmar Civil War',
    coords: [
      [92.2, 21.0], [92.1, 23.7], [93.0, 24.2], [94.0, 25.0],
      [94.5, 26.5], [96.0, 28.3], [97.5, 28.2], [98.5, 27.5],
      [98.8, 25.5], [100.2, 23.5], [101.0, 21.5], [100.5, 20.0],
      [99.0, 18.0], [98.5, 16.0], [98.5, 13.0], [97.5, 10.5],
      [97.0, 10.0], [97.8, 12.5], [97.5, 14.5], [96.5, 16.0],
      [95.5, 17.5], [94.5, 18.5], [93.5, 19.5], [92.5, 20.0],
      [92.2, 21.0],
    ],
    center: [96.5, 20],
    intensity: 'high',
    parties: ['Military junta (Tatmadaw)', 'NUG / PDF', 'Arakan Army (AA)', 'MNDAA / TNLA / KIA', 'Ethnic armed organizations'],
    casualties: '50,000+ (est.)',
    displaced: '3M+ internally displaced',
    keywords: ['myanmar', 'burma', 'rohingya', 'shan', 'rakhine', 'arakan army', 'kachin', 'pdf', 'nug', 'coup', 'resistance', 'junta', 'tatmadaw'],
    startDate: 'Feb 1, 2021',
    location: 'Myanmar (nationwide)',
    description: 'Civil war following 2021 military coup. Resistance forces and ethnic armed organizations have captured significant territory. Junta losing control of border regions. Multiple coordinated offensives ongoing.',
    keyDevelopments: ['Operation 1027 (Shan State)', 'Lashio capture by MNDAA', 'AA controls most of Rakhine', 'Myawaddy capture', 'Junta airstrikes on civilians', 'Resistance advances in Sagaing'],
  },
  {
    id: 'korean_dmz',
    name: 'Korean Demilitarized Zone',
    intensity: 'low',
    parties: ['Republic of Korea', "Democratic People's Republic of Korea", 'United Nations Command'],
    startDate: 'Jul 27, 1953',
    location: 'Korean Peninsula (MDL)',
    description: '250km-long, 4km-wide buffer zone along the Military Demarcation Line established by the 1953 Korean Armistice Agreement. Despite its name, one of the most heavily militarized borders in the world.',
    peaceAgreements: ['Korean Armistice Agreement (Jul 27, 1953)'],
    totalFatalities: '2,500,000+ (Korean War)',
    center: [127.27, 38.14],
    coords: [
      [126.0955, 37.7876],
      [126.2448, 37.8175],
      [126.3927, 37.857],
      [126.5117, 37.9068],
      [126.6219, 37.9468],
      [126.6735, 37.9672],
      [126.775, 37.9875],
      [126.8936, 38.0173],
      [127.0409, 38.0665],
      [127.1676, 38.1351],
      [127.3004, 38.2363],
      [127.4476, 38.2679],
      [127.5784, 38.2679],
      [127.7175, 38.2879],
      [127.8476, 38.2979],
      [127.994, 38.3174],
      [128.1079, 38.3653],
      [128.1834, 38.4324],
      [128.262, 38.5312],
      [128.342, 38.6312],
      [128.3744, 38.634],
      [128.378, 38.6088],
      [128.2979, 38.5088],
      [128.2166, 38.4076],
      [128.1321, 38.3347],
      [128.006, 38.2826],
      [127.8524, 38.2621],
      [127.7225, 38.2521],
      [127.5816, 38.2321],
      [127.4524, 38.2321],
      [127.3196, 38.2037],
      [127.1924, 38.1049],
      [127.0591, 38.0335],
      [126.9064, 37.9827],
      [126.785, 37.9525],
      [126.6865, 37.9328],
      [126.6381, 37.9132],
      [126.5283, 37.8732],
      [126.4073, 37.823],
      [126.2552, 37.7825],
      [126.1045, 37.7524],
      [126.0777, 37.7665],
      [126.0955, 37.7876],
    ],
  },
  {
    id: 'pak_afghan',
    name: 'Pakistan–Afghanistan Border Conflict',
    coords: [
      [72.50, 35.70],
      [69.40, 31.69],
      [65.95, 29.33],
      [64.90, 30.29],
      [71.02, 36.55],
      [72.50, 35.70],
    ],
    center: [69, 31.8],
    intensity: 'medium',
    parties: ['Pakistan (Military)', 'TTP', 'Afghan Taliban'],
    casualties: 'Ongoing military and civilian casualties',
    displaced: 'Displacement along border areas',
    keywords: ['pakistan', 'afghanistan', 'ttp', 'taliban', 'torkham', 'chaman', 'waziristan', 'kpk', 'border', 'cross-border', 'airstrike'],
    startDate: 'Feb 21, 2026',
    location: 'Pakistan–Afghanistan border (KPK, Balochistan, Federally Administered Tribal Areas)',
    description: 'Escalating tensions along the Pakistan–Afghanistan border. Pakistan has conducted cross-border strikes targeting TTP sanctuaries in Afghan territory, prompting border closures and diplomatic friction with the Taliban government. Long-running dispute over militant safe havens and border security.',
    keyDevelopments: ['Pakistan cross-border strikes in Afghanistan', 'TTP attacks in KPK', 'Torkham/Chaman crossing tensions', 'Militant infiltration', 'Border closures'],
  },
];
